db.driver=org.mariadb.jdbc.Driver
db.url=jdbc:mariadb://127.0.0.1:3306/AREX_TNMS?useUnicode=true&characterEncoding=UTF-8&useSSL=false
db.username=root
db.password=root
db.pool.maxActive=20
db.pool.maxIdle=10
db.pool.validationQuery=SELECT 1
