<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="true" %>
<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AREX TNMS 화면 시안</title>
  <style>
    @font-face{font-family:Pretendard;src:url('<%=request.getContextPath()%>/fonts/tnms/PretendardVariable.woff2') format('woff2-variations');font-style:normal;font-weight:45 920;font-display:swap}
    .planner-dashboard-frame{display:block;width:100%;height:100vh;border:0;background:#eef3f8}
    *{box-sizing:border-box}html,body,#root{width:100%;height:100%}body{margin:0;overflow:hidden;background:#07111f;color:#e8f1fb;font-family:Pretendard,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:14px}
    .app{width:100%;height:100vh;min-width:1180px;display:grid;grid-template-columns:clamp(220px,13.55vw,260px) minmax(0,1fr);overflow:hidden;background:radial-gradient(circle at 78% 8%,#142b46 0,#091523 34%,#07111f 68%)}
    .sidebar{min-width:0;min-height:0;background:linear-gradient(180deg,#071725 0,#06111d 100%);border-right:1px solid #20334a;padding:24px 16px;display:flex;flex-direction:column;overflow:hidden}
    .brand{display:flex;gap:12px;align-items:center;padding:2px 10px 24px;border-bottom:1px solid #20334a;margin-bottom:18px}.logo{width:44px;height:36px;border-radius:10px;background:linear-gradient(135deg,#1dc4dc,#1378ec);display:grid;place-items:center;color:white;font-weight:800;font-size:20px;box-shadow:0 6px 24px #0b91d244}.brand b{font-size:20px;letter-spacing:.5px}.brand small{display:block;color:#7892ad;margin-top:3px}
    .nav{min-height:0;overflow-x:hidden;overflow-y:auto;padding-right:4px;scrollbar-width:thin;scrollbar-color:#29455d transparent}.nav::-webkit-scrollbar,.content::-webkit-scrollbar,.table-scroll::-webkit-scrollbar,.route-scroll::-webkit-scrollbar{width:8px;height:8px}.nav::-webkit-scrollbar-thumb,.content::-webkit-scrollbar-thumb,.table-scroll::-webkit-scrollbar-thumb,.route-scroll::-webkit-scrollbar-thumb{background:#29455d;border-radius:8px}.nav-group{color:#607d99;font-size:11px;font-weight:700;letter-spacing:1.6px;margin:17px 12px 7px}.nav-item{height:36px;display:flex;align-items:center;gap:10px;color:#a9bed2;border-radius:8px;padding:0 12px;margin:2px 0;font-size:13px}.nav-item .dot{width:7px;height:7px;border-radius:50%;background:#3b526a;flex:0 0 auto}.nav-item.active{background:linear-gradient(90deg,#123e64,#0c2947);color:#fff;border:1px solid #1d5d8b;box-shadow:inset 3px 0 #24c1e0}.nav-item.active .dot{background:#33d4ee;box-shadow:0 0 10px #33d4ee}
    .side-footer{flex:0 0 auto;margin-top:12px;border-top:1px solid #20334a;padding:16px 10px 0;color:#6e88a2;font-size:12px;line-height:1.7}
    .main{display:flex;flex-direction:column;min-width:0;min-height:0}.topbar{height:72px;flex:0 0 72px;border-bottom:1px solid #24364a;background:#081624dd;display:flex;align-items:center;justify-content:space-between;padding:0 28px}.crumb{color:#6f8ca9;font-size:13px}.crumb b{color:#d8e7f5}.top-right{display:flex;align-items:center;gap:14px}.live{display:flex;align-items:center;gap:8px;padding:7px 12px;border:1px solid #25435b;border-radius:18px;background:#0b2132;color:#8bd9e7;font-size:12px}.live i{width:7px;height:7px;border-radius:50%;background:#35df9a;box-shadow:0 0 10px #35df9a}.user{padding-left:14px;border-left:1px solid #2d4054;color:#a9bed2}.user b{color:#e9f3fc;margin-right:4px}
    .content{padding:24px 28px 28px;overflow:auto;flex:1;min-width:0;min-height:0}.heading{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin-bottom:18px}.heading>div:first-child{min-width:0}.heading h1{font-size:25px;margin:0 0 5px;letter-spacing:-.5px}.heading p{margin:0;color:#728aa3;font-size:13px}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;flex:0 0 auto}.btn{height:34px;padding:0 14px;border-radius:7px;border:1px solid #31506b;background:#102438;color:#bdd0e2;font:600 12px Pretendard;white-space:nowrap}.btn.primary{background:linear-gradient(135deg,#1689e9,#16b4d3);border:0;color:#fff}.btn.danger{border-color:#7b3444;color:#ff9baa;background:#2b1720}.btn.sm{height:28px;padding:0 10px;font-size:11px}
    .grid{display:grid;gap:14px}.grid>*,.split>*{min-width:0}.cols-4{grid-template-columns:repeat(4,minmax(0,1fr))}.cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}.cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}.span-2{grid-column:span 2}.span-3{grid-column:span 3}.span-4{grid-column:1/-1}.page-section{margin-top:14px}.dashboard-main{grid-template-columns:minmax(0,3fr) minmax(320px,1fr);margin-top:14px}.dashboard-main>.card,.dashboard-main>.topology{height:330px}.dashboard-route{height:224px;margin-top:14px}.card{background:linear-gradient(180deg,#0c1e30ee,#091a2aee);border:1px solid #243d55;border-radius:12px;padding:16px;box-shadow:0 12px 28px #02091455;min-width:0}.card-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:13px;font-weight:700;color:#dbe9f5}.card-title small{color:#6f8aa3;font-weight:500}.kpi{height:104px;padding:16px 18px;position:relative;overflow:hidden}.kpi:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-20px;top:-24px;background:#1cb0da11;border:18px solid #1cb0da0d}.kpi .label{color:#819ab1;font-size:12px}.kpi .value{font-size:30px;font-weight:700;margin-top:8px;white-space:nowrap}.kpi .sub{position:absolute;right:16px;bottom:15px;color:#64d2e5;font-size:11px}.c-cyan{color:#4fd7e8}.c-green{color:#45df9a}.c-yellow{color:#ffcc66}.c-red{color:#ff7389}.muted{color:#7890a7}.chip{display:inline-flex;align-items:center;gap:6px;border:1px solid #35506b;border-radius:12px;padding:3px 8px;font-size:11px;color:#9eb4c7;background:#102336;white-space:nowrap}.chip:before{content:"";width:6px;height:6px;border-radius:50%;background:#45df9a}.chip.warn:before{background:#ffcc66}.chip.bad:before{background:#ff6f83}.chip.off:before{background:#74869a}.filter{display:flex;flex-wrap:wrap;gap:8px;align-items:center;background:#091827;border:1px solid #203951;padding:10px;border-radius:10px;margin-bottom:12px}.input{height:32px;min-width:145px;max-width:100%;padding:0 10px;border:1px solid #2b465f;border-radius:6px;background:#0c2032;color:#9fb7cc;font:12px Pretendard}.input.wide{min-width:260px;flex:0 1 320px}.filter .spacer{flex:1 1 18px}
    .table-scroll{width:100%;max-width:100%;overflow-x:auto}.table-scroll table{width:100%}table{width:100%;border-collapse:collapse;table-layout:fixed}table.table-wide{min-width:900px}table.table-wide-xl{min-width:1120px}th{height:34px;background:#10263a;color:#7892aa;font-size:11px;font-weight:600;text-align:left;padding:0 10px;border-bottom:1px solid #2b4156;white-space:nowrap}td{height:38px;padding:0 10px;color:#bbccdc;border-bottom:1px solid #1a3044;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px}tbody tr:hover{background:#0d2a40}.right{text-align:right}.center{text-align:center}.pager{display:flex;justify-content:center;gap:5px;margin-top:12px}.page{width:26px;height:26px;border:1px solid #29445d;border-radius:5px;display:grid;place-items:center;color:#7690aa;font-size:11px}.page.on{background:#147dc7;color:#fff;border-color:#147dc7}
    .progress{height:7px;border-radius:6px;background:#132d42;overflow:hidden}.progress i{display:block;height:100%;background:linear-gradient(90deg,#18a8d6,#3bd8b4);border-radius:6px}.progress.warn i{background:linear-gradient(90deg,#f3ad32,#ff6d65)}
    .topology{height:330px;position:relative;padding:0;overflow:hidden;background:radial-gradient(circle at center,#0f2b42,#091827 60%)}.topology svg{width:100%;height:100%}.node{position:absolute;width:148px;height:74px;border:1px solid #2c5979;border-radius:10px;background:#0d2538e8;padding:11px;box-shadow:0 10px 18px #02081288}.node b{display:block;font-size:12px;margin-bottom:4px}.node small{color:#6e8ca8}.node .node-status{position:absolute;right:10px;top:10px;width:8px;height:8px;border-radius:50%;background:#41df9b;box-shadow:0 0 9px #41df9b}.node.warn .node-status{background:#ffcb62;box-shadow:0 0 9px #ffcb62}.node.bad .node-status{background:#ff6d81;box-shadow:0 0 9px #ff6d81}.node.core{width:180px;height:90px;left:50%;top:50%;transform:translate(-50%,-50%);border-color:#23a9d5;background:linear-gradient(135deg,#0e3955,#0b2539);text-align:center;padding-top:17px}.node.core b{font-size:15px;color:#4bd7e9}
    .route-scroll{width:100%;overflow-x:auto;overflow-y:hidden;padding-bottom:4px}.route{height:150px;min-width:1240px;display:flex;align-items:center;padding:0 20px;overflow:visible}.station{flex:1;text-align:center;position:relative;min-width:78px}.station:before{content:"";height:4px;background:#178ac7;position:absolute;left:-50%;right:50%;top:28px}.station:first-child:before{display:none}.station i{display:block;margin:17px auto 9px;width:22px;height:22px;border-radius:50%;background:#0d2234;border:5px solid #29b9da;position:relative;z-index:2}.station.bad i{border-color:#ff6e82}.station.warn i{border-color:#ffcc62}.station b{font-size:10px;line-height:1.25;display:block;white-space:nowrap;transform:rotate(-18deg);transform-origin:center;color:#9db4c8}.station small{display:block;color:#526c85;margin-top:15px;font-size:9px}
    .system-row{display:grid;grid-template-columns:repeat(5,minmax(180px,1fr));gap:12px;overflow-x:auto}.sys-card{min-width:0;height:156px;border:1px solid #29455d;border-radius:10px;background:#0a1c2c;padding:14px;position:relative}.sys-card h3{font-size:14px;margin:0 0 5px;padding-right:66px}.sys-card p{font-size:11px;color:#718ca6;margin:0 0 16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sys-card .metric{display:flex;justify-content:space-between;color:#8fa6bb;font-size:11px;margin-top:8px}.sys-card .big-status{position:absolute;right:14px;top:14px}
    .charts{display:grid;grid-template-columns:repeat(24,1fr);align-items:end;height:150px;gap:5px;padding:12px 8px 0;border-left:1px solid #254058;border-bottom:1px solid #254058;background:linear-gradient(#1b364233 1px,transparent 1px);background-size:100% 30px}.bar{background:linear-gradient(180deg,#39d0df,#187ac4);border-radius:3px 3px 0 0;min-height:3px}.bar.warn{background:linear-gradient(180deg,#ffd16d,#e98737)}
    .linechart{height:160px;position:relative;border-left:1px solid #254058;border-bottom:1px solid #254058;background:linear-gradient(#1b364233 1px,transparent 1px);background-size:100% 32px}.linechart svg{width:100%;height:100%}
    .video-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.video{height:208px;border:1px solid #284760;border-radius:10px;background:linear-gradient(160deg,#102c40,#06101a);position:relative;overflow:hidden}.video:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 60px,#3da3bd08 61px),repeating-linear-gradient(0deg,transparent 0 40px,#3da3bd08 41px)}.video .cam{position:absolute;left:14px;top:12px;font-size:11px;color:#d3e4f2}.video .time{position:absolute;right:14px;top:12px;font:11px monospace;color:#78e5d8}.video .scene{position:absolute;left:14%;right:14%;bottom:16%;height:48%;border-bottom:5px solid #31556b;border-left:2px solid #29485f;transform:skew(-14deg);opacity:.8}.video.off{background:#101820}.video.off:after{content:"영상 신호 없음";position:absolute;inset:0;display:grid;place-items:center;color:#6f8292;font-weight:600}
    .gauge-row{display:flex;align-items:center;gap:12px;margin:12px 0}.gauge-row label{width:86px;color:#8ca5ba;font-size:11px}.gauge-row .progress{flex:1}.gauge-row b{width:42px;text-align:right;font-size:12px}
    .form-grid{display:grid;grid-template-columns:150px 1fr 150px 1fr;border-top:1px solid #2b4156;border-left:1px solid #2b4156}.form-grid div{min-height:44px;border-right:1px solid #2b4156;border-bottom:1px solid #2b4156;padding:11px}.form-grid .label{background:#10263a;color:#8199af;font-size:12px}.form-grid .field{color:#c4d4e2}
    .matrix th,.matrix td{text-align:center}.matrix td:first-child{text-align:left}.check{width:18px;height:18px;border-radius:4px;border:1px solid #365672;display:inline-grid;place-items:center;color:#fff}.check.on{background:#1594d0;border-color:#1594d0}.check.on:after{content:"✓";font-size:11px}
    .timeline{position:relative;padding-left:26px}.timeline:before{content:"";position:absolute;left:8px;top:6px;bottom:6px;width:2px;background:#21445d}.event{position:relative;padding:0 0 17px 8px}.event:before{content:"";position:absolute;left:-23px;top:4px;width:10px;height:10px;border:3px solid #29bdd8;border-radius:50%;background:#0b1c2c}.event b{font-size:12px}.event p{margin:4px 0 0;color:#778fa6;font-size:11px}
    .callout{border-left:3px solid #22b4d1;background:#0d2a3c;padding:10px 12px;color:#8fb4c8;font-size:11px;border-radius:4px}.legend{display:flex;gap:13px;color:#7990a7;font-size:11px}.legend span:before{content:"";display:inline-block;width:7px;height:7px;border-radius:50%;background:#42df9a;margin-right:5px}.legend .w:before{background:#ffcb62}.legend .b:before{background:#ff6f83}.legend .o:before{background:#6e8194}
    .mini-map{height:430px;position:relative;background:radial-gradient(circle at 55% 50%,#10334a,#081625 65%);border:1px solid #274157;border-radius:12px;overflow:hidden}.mini-map svg{position:absolute;inset:0;width:100%;height:100%}.map-point{position:absolute;width:132px;height:56px;border-radius:9px;background:#0c2234;border:1px solid #2f5873;padding:9px}.map-point b{display:block;font-size:11px}.map-point small{color:#6c879e;font-size:9px}.map-point i{position:absolute;right:9px;top:9px;width:8px;height:8px;background:#3fe09a;border-radius:50%}.map-point.warn i{background:#ffcb62}.map-point.bad i{background:#ff7183}
    .split{display:grid;grid-template-columns:minmax(280px,360px) minmax(0,1fr);gap:14px}.tree{padding:8px}.tree .row{height:37px;display:flex;align-items:center;padding:0 10px;border-radius:6px;color:#9eb4c8}.tree .row.sel{background:#113450;color:#fff}.tree .indent{margin-left:22px}.tree .indent2{margin-left:44px}.tree .count{margin-left:auto;color:#638099}.section-note{color:#5f7d98;font-size:11px;margin-top:8px}
    .donut{width:128px;height:128px;border-radius:50%;background:conic-gradient(#39d797 0 78%,#ffcc65 78% 91%,#ff7083 91% 97%,#4e6478 97%);position:relative;margin:auto}.donut:after{content:"";position:absolute;inset:25px;border-radius:50%;background:#0b1c2c}.donut b{position:absolute;z-index:2;inset:0;display:grid;place-items:center;font-size:22px}
    .stack{display:flex;height:13px;border-radius:8px;overflow:hidden;background:#243647}.stack i:nth-child(1){background:#38d59b}.stack i:nth-child(2){background:#ffca64}.stack i:nth-child(3){background:#ff7082}.stack i:nth-child(4){background:#677b8e}
    .nav-item.denied{opacity:.35;cursor:not-allowed!important}.logout{color:#8fa8bd;text-decoration:none;font-size:12px;border:1px solid #29455d;border-radius:7px;padding:7px 10px}.logout:hover{color:#fff;border-color:#3d6d8e}.modal-backdrop{position:fixed;inset:0;z-index:1000;background:#020913c9;display:grid;place-items:center;padding:24px}.modal-panel{width:min(760px,95vw);max-height:90vh;overflow:auto;background:#0a1c2c;border:1px solid #31516c;border-radius:14px;box-shadow:0 25px 80px #000a;padding:20px}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.modal-head h2{margin:0;font-size:19px}.modal-close{background:none;border:0;color:#8fa8bd;font-size:24px;cursor:pointer}.edit-form{display:grid;grid-template-columns:130px minmax(0,1fr) 130px minmax(0,1fr);border-top:1px solid #2b4156;border-left:1px solid #2b4156}.edit-form label,.edit-form>div{min-height:54px;border-right:1px solid #2b4156;border-bottom:1px solid #2b4156;padding:10px}.edit-form label{background:#10263a;color:#8da5ba;display:flex;align-items:center}.edit-form .full{grid-column:span 3}.form-control{width:100%;height:34px;border:1px solid #2b465f;border-radius:6px;background:#0c2032;color:#d5e5f2;padding:0 10px}.form-help{display:block;color:#6f8ba3;font-size:11px;margin-top:5px}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.tree .row.clickable{cursor:pointer}.tree .row.clickable:hover{background:#0e2b42}.perm-check{width:18px;height:18px;accent-color:#1594d0;cursor:pointer}.empty-row{text-align:center;color:#6e879e;height:86px}.toast{position:fixed;right:26px;bottom:26px;z-index:1200;padding:12px 16px;border:1px solid #2f5c76;border-radius:9px;background:#0c2b40;color:#d6eef7;box-shadow:0 12px 30px #0008}.toast.bad{border-color:#7b3444;background:#2b1720;color:#ffb1bc}
    @media(max-width:1500px){.content{padding:20px}.heading{align-items:flex-start}.kpi .value{font-size:26px}.kpi .sub{max-width:55%;text-align:right}.dashboard-main{grid-template-columns:minmax(0,2fr) minmax(300px,1fr)}}
    @media(max-width:1250px){.brand small,.side-footer{display:none}.sidebar{padding:20px 12px}.content{padding:18px}.topbar{padding:0 20px}.heading{flex-wrap:wrap}.cols-4{grid-template-columns:repeat(2,minmax(0,1fr))}.span-3,.span-4{grid-column:1/-1}.dashboard-main{grid-template-columns:1fr}.dashboard-main>.card,.dashboard-main>.topology{height:330px}.video-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.form-grid{grid-template-columns:120px minmax(0,1fr)}.form-grid .span-3{grid-column:span 1}}
  </style>
  <link rel="stylesheet" href="<%=request.getContextPath()%>/css/tnms/modern-ui.css" />
</head>
<body><div id="root"></div>
<script>
const CONTEXT_PATH='<%=request.getContextPath()%>';
let CURRENT_USER={userNm:'사용자'};
let CSRF_TOKEN='';
let PERMISSIONS={};
const NAV=[
 ['통합관제',['통합 대시보드','역사·선로 현황']],
 ['시스템 관리',['연동시스템 관리','장비 관리','교환기 관리','CCTV 상태관리','CCTV 영상관리','SCADA 출입보안']],
 ['수집·성능',['연동주기 관리','임계치 관리','성능관리','Raw 데이터 관리']],
 ['장애관리',['실시간 장애','장애이력·조치','장애 예외설정','장애유형 관리']],
 ['보고서',['장애·성능 보고서']],
 ['운영설정',['사용자 계정 설정','권한 관리','계정 신청 현황','알림·SMS 설정','공통코드·UI 설정','작업로그 조회']]
];
const S={
 dashboard:{menu:'통합 대시보드',title:'통합 대시보드',desc:'5종 연동시스템, 장비, 역사·선로와 실시간 장애를 한 화면에서 확인합니다.'},
 route:{menu:'역사·선로 현황',title:'역사·선로 현황',desc:'공항철도 역사와 선로 구간별 통신설비 상태를 계층형 맵으로 확인합니다.'},
 systems:{menu:'연동시스템 관리',title:'연동시스템 관리',desc:'5개 운영시스템의 연결정보, 프로토콜, 수집상태와 서버 상태를 관리합니다.'},
 equipment:{menu:'장비 관리',title:'장비 관리',desc:'TNMS에 등록된 모든 관리 장비와 구성 변경이력을 조회합니다.'},
 switch:{menu:'교환기 관리',title:'교환기 관리',desc:'교환기 서버와 교환기 소프트웨어 노드의 상태·성능·알람을 모니터링합니다.'},
 cctv:{menu:'CCTV 상태관리',title:'CCTV 상태관리',desc:'약 1,000대 CCTV를 역사·그룹·상태별로 조회하고 장애 장비를 선별합니다.'},
 video:{menu:'CCTV 영상관리',title:'CCTV 영상관리',desc:'선택한 CCTV의 실시간 영상을 다분할 화면으로 확인합니다.'},
 scada:{menu:'SCADA 출입보안',title:'SCADA 출입보안',desc:'역사 시설 출입통제 장치와 출입 이벤트 상태를 모니터링합니다.'},
 cycle:{menu:'연동주기 관리',title:'연동주기 관리',desc:'시스템별 데이터 수집주기와 30초 이내 상태감시 주기를 설정합니다.'},
 threshold:{menu:'임계치 관리',title:'임계치 관리',desc:'CPU·메모리·트래픽·에러패킷 등 지표별 다단계 임계치를 설정합니다.'},
 performance:{menu:'성능관리',title:'성능관리',desc:'연동시스템과 장비의 실시간·기간별 성능 추이를 조회합니다.'},
 raw:{menu:'Raw 데이터 관리',title:'Raw 데이터 관리',desc:'수신 원본과 집계 데이터의 저장 현황·보존기간·수집 품질을 확인합니다.'},
 faults:{menu:'실시간 장애',title:'실시간 장애',desc:'현재 발생 중인 장애를 판단하고 임시조치·이관·제어를 수행합니다.'},
 faultHistory:{menu:'장애이력·조치',title:'장애이력·조치',desc:'종료된 장애의 발생부터 완료조치까지 전체 이력을 조회합니다.'},
 exceptions:{menu:'장애 예외설정',title:'장애 예외설정',desc:'정기점검 등 계획된 시간에는 선택 장비의 장애 이벤트를 억제합니다.'},
 faultTypes:{menu:'장애유형 관리',title:'장애유형 관리',desc:'설비 EMS에서 연동되는 장애유형, 등급, 판단기준과 사용여부를 관리합니다.'},
 reports:{menu:'장애·성능 보고서',title:'장애·성능 보고서',desc:'장애 조치 및 성능 통계를 기간·설비별 보고서로 조회하고 출력합니다.'},
 users:{menu:'사용자 계정 설정',title:'사용자 계정 설정',desc:'TNMS 사용자 계정의 상태·소속·권한을 관리합니다.'},
 auth:{menu:'권한 관리',title:'권한 관리',desc:'역할별 화면 조회·등록·수정·삭제·제어 권한을 설정합니다.'},
 applications:{menu:'계정 신청 현황',title:'계정 신청 현황',desc:'사용자 계정 사용 신청을 검토하고 승인·반려합니다.'},
 notify:{menu:'알림·SMS 설정',title:'알림·SMS 설정',desc:'장애등급별 전송그룹과 SMS 수신 대상을 관리합니다.'},
 settings:{menu:'공통코드·UI 설정',title:'공통코드·UI 설정',desc:'이벤트 등급 색상, 목록 행수와 공통코드를 관리합니다.'},
 logs:{menu:'작업로그 조회',title:'작업로그 조회',desc:'사용자의 로그인 및 웹 화면 작업 이력을 추적합니다.'}
};
const MENU_KEY=Object.fromEntries(Object.entries(S).map(([k,v])=>[v.menu,k]));
function sidebar(active){return `<aside class="sidebar"><div class="brand"><div class="logo">A</div><div><b>AREX TNMS</b><small>통합 네트워크 관리시스템</small></div></div><div class="nav">${NAV.map(([g,items])=>`<div class="nav-group">${g}</div>${items.map(x=>{const key=MENU_KEY[x]||'';const allowed=hasPermission(key,'listAuthrtYn');return `<div class="nav-item ${x===active?'active':''} ${allowed?'':'denied'}" data-key="${key}" title="${allowed?'':'접근 권한 없음'}"><i class="dot"></i>${x}</div>`}).join('')}`).join('')}</div><div class="side-footer">수집상태 <span class="c-green">정상</span><br>DB 연동: 로그인·사용자·권한<br>TNMS v1.0</div></aside>`}
function layout(key,body,actions=''){const s=S[key];return `<div class="app">${sidebar(s.menu)}<main class="main"><header class="topbar"><div class="crumb">HOME &nbsp;/&nbsp; <b>${s.menu}</b></div><div class="top-right"><div class="live"><i></i> 실시간 수집 중 · 5초 전</div><div class="user"><b>${escapeHtml(CURRENT_USER.userNm||CURRENT_USER.userId||'사용자')}</b> 님</div><a class="logout" href="${CONTEXT_PATH}/login/logout.do">로그아웃</a></div></header><section class="content"><div class="heading"><div><h1>${s.title}</h1><p>${s.desc}</p></div><div class="actions">${actions}</div></div>${body}</section></main></div>`}
const chip=(x,t='')=>`<span class="chip ${t}">${x}</span>`;
const btn=(x,c='')=>`<button class="btn ${c}">${x}</button>`;
const route=()=>['서울역','공덕','홍대입구','디지털미디어시티','마곡나루','김포공항','계양','검암','청라국제도시','영종','운서','공항화물청사','인천공항1터미널','인천공항2터미널'].map((x,i)=>`<div class="station ${i===7?'warn':i===11?'bad':''}"><i></i><b>${x}</b><small>${i===7?'주의':i===11?'장애':'정상'}</small></div>`).join('');
function topology(){return `<div class="topology card"><svg viewBox="0 0 1000 330"><g stroke="#1d5876" stroke-width="2" fill="none"><path d="M500 165 L165 62M500 165 L500 45M500 165 L835 62M500 165 L250 270M500 165 L750 270"/><circle cx="500" cy="165" r="128" stroke="#17435d" stroke-dasharray="6 8"/></g></svg><div class="node core"><span class="node-status"></span><b>TNMS 통합NMS 서버</b><small>CPU 43% · MEM 58%<br>수집 1,487 node</small></div><div class="node" style="left:7%;top:8%"><span class="node-status"></span><b>EMS 전송설비</b><small>정상 · 126 장비</small></div><div class="node" style="left:42%;top:4%"><span class="node-status"></span><b>EMS 행선안내</b><small>정상 · 84 장비</small></div><div class="node" style="right:7%;top:8%"><span class="node-status"></span><b>SCADA 보안</b><small>정상 · 262 장비</small></div><div class="node warn" style="left:15%;bottom:6%"><span class="node-status"></span><b>전화교환설비</b><small>주의 · 15 / 500</small></div><div class="node bad" style="right:15%;bottom:6%"><span class="node-status"></span><b>영상감시설비</b><small>장애 · 3 / 1,000</small></div></div>`}
function dashboard(){return layout('dashboard',`
  <div class="grid cols-4 dashboard-kpis">
    <div class="card kpi"><div class="label">연동시스템</div><div class="value c-cyan">5 <small class="muted" style="font-size:13px">종</small></div><div class="sub">정상 4 · 주의 1</div></div>
    <div class="card kpi"><div class="label">관리 장비</div><div class="value">1,472</div><div class="sub">온라인 1,454</div></div>
    <div class="card kpi"><div class="label">현재 장애</div><div class="value c-red">7</div><div class="sub">심각 1 · 경고 2 · 주의 4</div></div>
    <div class="card kpi"><div class="label">오늘 수집 성공률</div><div class="value c-green">99.82%</div><div class="sub">최근 5분 기준</div></div>
  </div>
  <div class="grid dashboard-main">
    ${topology()}
    <div class="card"><div class="card-title">실시간 장애 <small>최근 5건</small></div><table><tr><th>등급</th><th>대상</th><th>발생시각</th></tr><tr><td>${chip('심각','bad')}</td><td>화물청사 CCTV-0821</td><td>16:39:22</td></tr><tr><td>${chip('경고','warn')}</td><td>교환 SW-03</td><td>16:35:08</td></tr><tr><td>${chip('경고','warn')}</td><td>검암 역사 SW-12</td><td>16:31:14</td></tr><tr><td>${chip('주의')}</td><td>SCADA 게이트-17</td><td>16:25:47</td></tr><tr><td>${chip('주의')}</td><td>CCTV-0655</td><td>16:21:05</td></tr></table></div>
  </div>
  <div class="card dashboard-route"><div class="card-title">공항철도 역사·선로 상태 <div class="legend"><span>정상</span><span class="w">주의</span><span class="b">장애</span></div></div><div class="route">${route()}</div></div>
`);}
function routeScreen(){return layout('route',`<div class="grid cols-3"><div class="card span-3" style="height:220px"><div class="card-title">공항철도 전 구간 <div class="legend"><span>정상</span><span class="w">주의</span><span class="b">장애</span></div></div><div class="route" style="height:160px">${route()}</div></div><div class="card span-2"><div class="card-title">구간·역사 계층형 상태 맵 <small>장비 클릭 시 상세 이동</small></div><div class="mini-map"><svg viewBox="0 0 900 430"><path d="M70 330 C180 300,210 160,340 190 S520 310,650 170 S790 75,845 105" stroke="#1d789e" stroke-width="6" fill="none"/><path d="M70 330 C180 300,210 160,340 190 S520 310,650 170 S790 75,845 105" stroke="#41cde2" stroke-width="2" fill="none" stroke-dasharray="4 8"/></svg><div class="map-point" style="left:4%;top:68%"><i></i><b>서울역</b><small>장비 112 · 정상</small></div><div class="map-point" style="left:22%;top:35%"><i></i><b>김포공항</b><small>장비 138 · 정상</small></div><div class="map-point warn" style="left:43%;top:61%"><i></i><b>검암</b><small>주의 2건</small></div><div class="map-point" style="left:64%;top:30%"><i></i><b>운서</b><small>장비 96 · 정상</small></div><div class="map-point bad" style="right:3%;top:10%"><i></i><b>공항화물청사</b><small>장애 1건</small></div></div></div><div class="card"><div class="card-title">선택 역사 현황 <small>검암</small></div><div class="donut"><b>98%</b></div><div style="margin:22px 5px 10px" class="stack"><i style="width:92%"></i><i style="width:5%"></i><i style="width:2%"></i><i style="width:1%"></i></div><table><tr><th>설비</th><th class="right">전체</th><th class="right">장애</th></tr><tr><td>CCTV</td><td class="right">72</td><td class="right c-red">1</td></tr><tr><td>교환기</td><td class="right">24</td><td class="right">0</td></tr><tr><td>SCADA 보안</td><td class="right">38</td><td class="right c-yellow">1</td></tr><tr><td>전송/행선안내</td><td class="right">31</td><td class="right">0</td></tr></table></div></div>`);}
const systemData=[['EMS 전송설비','SNMP v3','10.21.10.11','126','정상'],['EMS 행선안내','REST API','10.21.10.21','84','정상'],['SCADA 출입보안','TCP/IP','10.21.10.31','262','정상'],['전화교환설비','SNMP v2c','10.21.10.41','500','주의'],['영상감시설비','REST API','10.21.10.51','1,000','장애']];
function systems(){return layout('systems',`<div class="grid cols-3"><div class="card span-3"><div class="system-row">${systemData.map((x,i)=>`<div class="sys-card"><div class="big-status">${chip(x[4],i===3?'warn':i===4?'bad':'')}</div><h3>${x[0]}</h3><p>${x[1]} · ${x[2]}</p><div class="metric"><span>관리 노드</span><b>${x[3]}</b></div><div class="metric"><span>최종수신</span><b>${i===4?'42초 전':'5초 전'}</b></div></div>`).join('')}</div></div><div class="card span-2"><div class="card-title">연동시스템 목록 <small>연결정보·프로토콜</small></div><div class="filter"><select class="input"><option>전체 상태</option></select><input class="input wide" value="시스템명 검색"><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th style="width:160px">시스템명</th><th>프로토콜</th><th>서버 IP</th><th>수집주기</th><th>최종수신</th><th>상태</th></tr>${systemData.map((x,i)=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${i===4?'30초':'60초'}</td><td>${i===4?'16:41:28':'16:42:05'}</td><td>${chip(x[4],i===3?'warn':i===4?'bad':'')}</td></tr>`).join('')}</table></div><div class="card"><div class="card-title">선택 시스템 정보</div><div class="form-grid" style="grid-template-columns:105px 1fr"><div class="label">시스템명</div><div class="field">영상감시설비</div><div class="label">모델명</div><div class="field">VMS Gateway 3.2</div><div class="label">S/W 버전</div><div class="field">v3.2.14</div><div class="label">설치일자</div><div class="field">2026-06-10</div><div class="label">상태감시</div><div class="field">30초</div><div class="label">연동업체</div><div class="field">영상감시 구축사</div></div><div class="callout" style="margin-top:14px">구성정보 수정 시 변경 전·후 값과 작업자를 History로 저장합니다.</div></div></div>`,btn('신규 등록','primary'))}
function equipment(){const rows=[['EQ-000821','CCTV-0821','CCTV','공항화물청사','10.32.8.21','장애'],['EQ-001203','PBX-SW-03','교환기 SW','인천공항1터미널','10.41.3.3','주의'],['EQ-000442','SCADA-GATE-17','출입통제','검암','10.52.4.17','주의'],['EQ-000101','TX-SW-001','전송 스위치','서울역','10.11.1.1','정상'],['EQ-000904','CCTV-0904','CCTV','인천공항2터미널','10.32.9.4','정상'],['EQ-001328','PIDS-0328','행선안내','홍대입구','10.22.3.28','정상'],['EQ-001401','PBX-CORE-01','교환 서버','통합전산실','10.41.1.1','정상']];return layout('equipment',`<div class="card"><div class="filter"><select class="input"><option>전체 시스템</option></select><select class="input"><option>전체 역사</option></select><select class="input"><option>전체 상태</option></select><input class="input wide" value="장비명 / IP / 관리번호"><div class="spacer"></div>${btn('검색','primary')}${btn('Excel')}</div><div class="card-title">전체 장비 <small>총 1,472건 · 구성 동기화 16:40 완료</small></div><table><tr><th style="width:120px">관리번호</th><th>장비명</th><th>장비구분</th><th>설치위치</th><th>IP주소</th><th>모델명</th><th>S/W버전</th><th>설치일자</th><th>상태</th></tr>${rows.map((x,i)=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${i<2?'AREX-CAM X4':'AREX-NET '+(i+1)}</td><td>v${2+i}.1.${i+3}</td><td>2026-0${(i%6)+1}-12</td><td>${chip(x[5],x[5]==='장애'?'bad':x[5]==='주의'?'warn':'')}</td></tr>`).join('')}</table><div class="pager"><div class="page">‹</div><div class="page on">1</div><div class="page">2</div><div class="page">3</div><div class="page">…</div><div class="page">74</div><div class="page">›</div></div></div>`,btn('변경장비 조회')+btn('장비 동기화 현황')+btn('장비 등록','primary'))}
function switchScreen(){return layout('switch',`<div class="grid cols-4"><div class="card kpi"><div class="label">교환기 관리 노드</div><div class="value">500</div><div class="sub">온라인 497</div></div><div class="card kpi"><div class="label">교환 서버 CPU</div><div class="value c-green">43.2%</div><div class="sub">주의 70% 이상</div></div><div class="card kpi"><div class="label">교환 서버 메모리</div><div class="value c-yellow">68.5%</div><div class="sub">주의 임계 근접</div></div><div class="card kpi"><div class="label">현재 알람</div><div class="value c-red">3</div><div class="sub">경고 1 · 주의 2</div></div><div class="card span-2"><div class="card-title">교환 서버 상태 <small>PBX-CORE-01</small></div><div class="gauge-row"><label>CPU 사용률</label><div class="progress"><i style="width:43%"></i></div><b>43%</b></div><div class="gauge-row"><label>메모리 사용률</label><div class="progress warn"><i style="width:69%"></i></div><b class="c-yellow">69%</b></div><div class="gauge-row"><label>디스크 사용률</label><div class="progress"><i style="width:54%"></i></div><b>54%</b></div><div class="gauge-row"><label>통화채널</label><div class="progress"><i style="width:38%"></i></div><b>191</b></div><div class="linechart"><svg viewBox="0 0 700 160"><polyline points="0,118 40,100 80,104 120,88 160,96 200,72 240,80 280,62 320,74 360,58 400,54 440,68 480,51 520,64 560,45 600,56 650,48 700,59" fill="none" stroke="#39d5e0" stroke-width="3"/><polyline points="0,132 40,130 80,124 120,128 160,117 200,120 240,111 280,104 320,101 360,98 400,95 440,90 480,87 520,84 560,80 600,77 650,74 700,70" fill="none" stroke="#ffca62" stroke-width="2"/></svg></div></div><div class="card span-2"><div class="card-title">교환기 SW 상태 <small>주의 이상 우선</small></div><table><tr><th>노드명</th><th>역사</th><th>등록상태</th><th>트래픽</th><th>에러패킷</th><th>상태</th></tr><tr><td>PBX-SW-03</td><td>인천공항1터미널</td><td>497 / 500</td><td>82.3 Mbps</td><td class="c-red">4.12%</td><td>${chip('경고','warn')}</td></tr><tr><td>PBX-SW-07</td><td>검암</td><td>128 / 128</td><td>43.1 Mbps</td><td class="c-yellow">1.07%</td><td>${chip('주의','warn')}</td></tr><tr><td>PBX-SW-12</td><td>서울역</td><td>256 / 256</td><td>55.8 Mbps</td><td>0.04%</td><td>${chip('정상')}</td></tr><tr><td>PBX-SW-21</td><td>운서</td><td>96 / 96</td><td>19.8 Mbps</td><td>0.02%</td><td>${chip('정상')}</td></tr></table><div class="card-title" style="margin-top:20px">최근 알람</div><div class="timeline"><div class="event"><b>PBX-SW-03 에러패킷 임계치 초과</b><p>16:35:08 · 경고 · 4.12%</p></div><div class="event"><b>PBX-SW-07 등록단말 일시 감소</b><p>16:22:31 · 주의 · 자동복구</p></div><div class="event"><b>PBX-CORE-01 메모리 임계치 근접</b><p>16:08:17 · 주의 · 68.5%</p></div></div></div></div>`)}
function cctv(){const r=[['CCTV-0821','공항화물청사','화물청사 동측 승강장','10.32.8.21','신호없음','장애'],['CCTV-0655','검암','2번 출입구','10.32.6.55','프레임저하','주의'],['CCTV-0412','김포공항','환승통로 A','10.32.4.12','정상','정상'],['CCTV-0904','인천공항2터미널','출국장 서측','10.32.9.4','정상','정상'],['CCTV-0308','홍대입구','지하 2층 대합실','10.32.3.8','정상','정상'],['CCTV-0711','운서','1번 승강장','10.32.7.11','정상','정상'],['CCTV-0120','서울역','직통열차 게이트','10.32.1.20','정상','정상'],['CCTV-0522','계양','환승통로 B','10.32.5.22','정상','정상']];return layout('cctv',`<div class="grid cols-4"><div class="card kpi"><div class="label">전체 CCTV</div><div class="value">1,000</div><div class="sub">14개 역사</div></div><div class="card kpi"><div class="label">정상</div><div class="value c-green">982</div><div class="sub">98.2%</div></div><div class="card kpi"><div class="label">주의</div><div class="value c-yellow">15</div><div class="sub">프레임·화질 저하</div></div><div class="card kpi"><div class="label">장애</div><div class="value c-red">3</div><div class="sub">신호없음·접속불가</div></div><div class="card span-4"><div class="filter"><select class="input"><option>전체 역사</option></select><select class="input"><option>전체 구역</option></select><select class="input"><option>전체 상태</option></select><input class="input wide" value="CCTV명 / IP / 설치위치"><div class="spacer"></div>${btn('검색','primary')}${btn('선택 영상보기')}</div><div class="card-title">CCTV 상태 목록 <small>1,000건 · 페이지당 20건</small></div><table><tr><th style="width:42px"><span class="check"></span></th><th>CCTV명</th><th>역사</th><th>설치위치</th><th>IP주소</th><th>영상상태</th><th>최근 응답</th><th>상태</th><th>조작</th></tr>${r.map(x=>`<tr><td><span class="check"></span></td><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${x[5]==='장애'?'42초 전':'4초 전'}</td><td>${chip(x[5],x[5]==='장애'?'bad':x[5]==='주의'?'warn':'')}</td><td>${btn('영상','sm')}</td></tr>`).join('')}</table><div class="pager"><div class="page">‹</div><div class="page on">1</div><div class="page">2</div><div class="page">3</div><div class="page">…</div><div class="page">50</div><div class="page">›</div></div></div></div>`,btn('CCTV 등록','primary'))}
function video(){return layout('video',`<div class="filter"><select class="input"><option>공항화물청사</option></select><select class="input"><option>전체 구역</option></select><select class="input"><option>9분할</option></select><input class="input wide" value="CCTV명 검색"><div class="spacer"></div>${btn('영상 배치 저장')}${btn('전체화면','primary')}</div><div class="video-grid">${[['CCTV-0818 · 화물청사 서측',''],['CCTV-0819 · 화물청사 중앙',''],['CCTV-0820 · 화물청사 동측',''],['CCTV-0821 · 동측 승강장','off'],['CCTV-0822 · 화물 적재구역',''],['CCTV-0823 · 출입통제구역',''],['CCTV-0824 · 대합실',''],['CCTV-0825 · 직원통로',''],['CCTV-0826 · 외곽 주차장','']].map((x,i)=>`<div class="video ${x[1]}"><span class="cam">${x[0]}</span><span class="time">2026-08-04 16:42:${String(10+i).padStart(2,'0')}</span><div class="scene"></div></div>`).join('')}</div>`,btn('PTZ 제어')+btn('이상 영상만 보기'))}
function scada(){return layout('scada',`<div class="grid cols-4"><div class="card kpi"><div class="label">출입통제 장치</div><div class="value">262</div><div class="sub">온라인 260</div></div><div class="card kpi"><div class="label">정상</div><div class="value c-green">260</div><div class="sub">99.2%</div></div><div class="card kpi"><div class="label">비정상 개방</div><div class="value c-red">1</div><div class="sub">확인 필요</div></div><div class="card kpi"><div class="label">통신 장애</div><div class="value c-yellow">1</div><div class="sub">SCADA-GATE-17</div></div><div class="card span-2"><div class="card-title">역사별 출입보안 상태</div><table><tr><th>역사</th><th>장치</th><th>온라인</th><th>비정상</th><th>상태</th></tr><tr><td>검암</td><td>38</td><td>37</td><td class="c-yellow">1</td><td>${chip('주의','warn')}</td></tr><tr><td>공항화물청사</td><td>31</td><td>31</td><td class="c-red">1</td><td>${chip('경고','bad')}</td></tr><tr><td>인천공항1터미널</td><td>52</td><td>52</td><td>0</td><td>${chip('정상')}</td></tr><tr><td>인천공항2터미널</td><td>48</td><td>48</td><td>0</td><td>${chip('정상')}</td></tr><tr><td>기타 역사</td><td>93</td><td>92</td><td>0</td><td>${chip('정상')}</td></tr></table><div class="callout" style="margin-top:18px">※ 본 시안은 SCADA를 시설 출입통제로 가정했습니다. AFC 승객 카드 집계라면 데이터 항목과 화면을 별도로 재구성해야 합니다.</div></div><div class="card span-2"><div class="card-title">최근 출입·상태 이벤트 <small>실시간</small></div><div class="timeline"><div class="event"><b class="c-red">화물청사 직원통로 비정상 개방</b><p>16:41:51 · DOOR-CT-008 · 미승인 개방</p></div><div class="event"><b class="c-yellow">검암 출입통제기 통신 응답 지연</b><p>16:39:12 · SCADA-GATE-17 · 31.2초</p></div><div class="event"><b>인천공항1터미널 보안문 정상 폐쇄</b><p>16:35:29 · DOOR-T1-032</p></div><div class="event"><b>서울역 직원통로 정상 출입</b><p>16:32:44 · DOOR-SL-011</p></div></div></div></div>`)}
function cycle(){const r=[['EMS 전송설비','성능','SNMP v3','60초','30초','16:42:00','사용'],['EMS 행선안내','상태','REST API','60초','30초','16:42:01','사용'],['SCADA 출입보안','상태/알람','TCP/IP','60초','30초','16:42:02','사용'],['전화교환설비','성능/알람','SNMP v2c','60초','30초','16:41:58','사용'],['영상감시설비','상태','REST API','30초','30초','16:41:28','사용']];return layout('cycle',`<div class="card"><div class="callout" style="margin-bottom:14px">성능·구성 데이터는 기본 5분, 최소 1분 단위로 변경할 수 있습니다. 생존 상태감시는 30초 이내로 별도 관리합니다.</div><div class="filter"><select class="input"><option>전체 시스템</option></select><select class="input"><option>전체 데이터 구분</option></select><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>시스템명</th><th>데이터 구분</th><th>프로토콜</th><th>수집주기</th><th>상태감시 주기</th><th>최근 실행</th><th>다음 실행</th><th>사용여부</th><th>설정</th></tr>${r.map((x,i)=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${x[5]}</td><td>16:${42+i}:${30+i}</td><td>${chip(x[6])}</td><td>${btn('수정','sm')}</td></tr>`).join('')}</table><div class="card-title" style="margin-top:24px">수집 실행 현황 <small>최근 24시간</small></div><div class="charts">${[70,84,76,91,88,93,96,94,86,90,97,96,93,94,91,92,95,96,98,95,89,94,97,91].map((h,i)=>`<i class="bar ${i===8?'warn':''}" style="height:${h}%"></i>`).join('')}</div></div>`,btn('수집주기 등록','primary'))}
function threshold(){const rows=[['서버','CPU 사용률','%','70','85','95','5분','사용'],['서버','메모리 사용률','%','70','85','95','5분','사용'],['네트워크','트래픽 사용률','%','65','80','90','3분','사용'],['네트워크','에러패킷률','%','1','3','5','1분','사용'],['CCTV','응답 지연시간','초','10','20','30','1회','사용'],['CCTV','프레임 손실률','%','3','7','12','3분','사용'],['교환기','등록단말 감소율','%','5','10','20','1분','사용']];return layout('threshold',`<div class="card"><div class="filter"><select class="input"><option>전체 시스템</option></select><select class="input"><option>전체 지표</option></select><select class="input"><option>사용 중</option></select><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>대상 구분</th><th>성능지표</th><th>단위</th><th class="center">주의</th><th class="center">경고</th><th class="center">심각</th><th>지속조건</th><th>사용여부</th><th>수정</th></tr>${rows.map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td><td class="center c-yellow">${x[3]}</td><td class="center" style="color:#ff9f5e">${x[4]}</td><td class="center c-red">${x[5]}</td><td>${x[6]}</td><td>${chip(x[7])}</td><td>${btn('수정','sm')}</td></tr>`).join('')}</table><div class="grid cols-3" style="margin-top:18px"><div class="card"><div class="card-title">주의</div><p class="muted">운영자 확인이 필요한 상태. 노란색 알람으로 표출합니다.</p></div><div class="card"><div class="card-title">경고</div><p class="muted">장애 가능성이 높은 상태. 주황색 알람과 SMS를 전송합니다.</p></div><div class="card"><div class="card-title">심각</div><p class="muted">서비스 영향이 예상되는 상태. 적색 알람과 즉시 통보합니다.</p></div></div></div>`,btn('임계치 등록','primary'))}
function performanceScreen(){return layout('performance',`<div class="grid cols-4"><div class="card kpi"><div class="label">평균 CPU</div><div class="value c-green">41.8%</div><div class="sub">전일 대비 +1.2%</div></div><div class="card kpi"><div class="label">평균 메모리</div><div class="value c-yellow">63.4%</div><div class="sub">전일 대비 +4.8%</div></div><div class="card kpi"><div class="label">평균 트래픽</div><div class="value">382 Mbps</div><div class="sub">최대 611 Mbps</div></div><div class="card kpi"><div class="label">수집 성공률</div><div class="value c-green">99.82%</div><div class="sub">누락 0.18%</div></div><div class="card span-3"><div class="filter"><select class="input"><option>전화교환설비</option></select><select class="input"><option>PBX-CORE-01</option></select><select class="input"><option>최근 24시간</option></select><div class="spacer"></div>${btn('조회','primary')}</div><div class="card-title">성능 추이 <div class="legend"><span>CPU</span><span class="w">메모리</span></div></div><div class="linechart" style="height:330px"><svg viewBox="0 0 1050 330"><polyline points="0,230 60,210 120,218 180,174 240,190 300,160 360,180 420,138 480,150 540,126 600,145 660,112 720,132 780,105 840,125 900,98 960,120 1050,108" fill="none" stroke="#3dd5df" stroke-width="4"/><polyline points="0,190 60,182 120,186 180,172 240,164 300,158 360,151 420,148 480,139 540,132 600,128 660,121 720,116 780,111 840,105 900,101 960,96 1050,90" fill="none" stroke="#ffca62" stroke-width="3"/></svg></div></div><div class="card"><div class="card-title">장비별 TOP 5 <small>메모리</small></div><table><tr><th>장비</th><th class="right">사용률</th></tr><tr><td>PBX-CORE-01</td><td class="right c-yellow">68.5%</td></tr><tr><td>VMS-GW-01</td><td class="right">64.2%</td></tr><tr><td>SCADA-CORE</td><td class="right">61.9%</td></tr><tr><td>EMS-TX-01</td><td class="right">58.4%</td></tr><tr><td>PIDS-EMS-01</td><td class="right">55.7%</td></tr></table><div class="card-title" style="margin-top:20px">시간대별 수집량</div><div class="charts" style="height:180px">${[55,63,70,61,76,82,78,88,95,84,79,91].map(h=>`<i class="bar" style="height:${h}%"></i>`).join('')}</div></div></div>`,btn('Excel')+btn('보고서 출력'))}
function raw(){return layout('raw',`<div class="grid cols-4"><div class="card kpi"><div class="label">Raw 데이터</div><div class="value">2.84 TB</div><div class="sub">보존 3개월</div></div><div class="card kpi"><div class="label">1시간 통계</div><div class="value">164 GB</div><div class="sub">보존 1년</div></div><div class="card kpi"><div class="label">일 통계</div><div class="value">18.7 GB</div><div class="sub">보존 3년</div></div><div class="card kpi"><div class="label">DB 사용률</div><div class="value c-yellow">67.3%</div><div class="sub">예상 잔여 96일</div></div><div class="card span-3"><div class="filter"><select class="input"><option>전체 시스템</option></select><select class="input"><option>Raw 데이터</option></select><input class="input" value="2026-08-04"><input class="input" value="2026-08-04"><div class="spacer"></div>${btn('조회','primary')}</div><table><tr><th>수집일시</th><th>시스템</th><th>장비</th><th>지표코드</th><th class="right">측정값</th><th>단위</th><th>수집상태</th></tr><tr><td>16:42:10</td><td>전화교환</td><td>PBX-CORE-01</td><td>CPU_USGRT</td><td class="right">43.20</td><td>%</td><td>${chip('성공')}</td></tr><tr><td>16:42:10</td><td>전화교환</td><td>PBX-CORE-01</td><td>MMRY_USGRT</td><td class="right">68.50</td><td>%</td><td>${chip('성공')}</td></tr><tr><td>16:42:08</td><td>영상감시</td><td>CCTV-0821</td><td>RSPNS_SEC</td><td class="right c-red">42.00</td><td>초</td><td>${chip('지연','warn')}</td></tr><tr><td>16:42:05</td><td>SCADA</td><td>GATE-017</td><td>CNTN_YN</td><td class="right">1</td><td>-</td><td>${chip('성공')}</td></tr><tr><td>16:42:01</td><td>전송설비</td><td>TX-SW-001</td><td>TRFC_USGRT</td><td class="right">44.82</td><td>%</td><td>${chip('성공')}</td></tr></table><div class="card-title" style="margin-top:22px">일별 저장량 추이</div><div class="charts" style="height:180px">${[58,63,66,70,68,74,79,84,82,88,91,94,90,96,92,95].map((h,i)=>`<i class="bar ${i===13?'warn':''}" style="height:${h}%"></i>`).join('')}</div></div><div class="card"><div class="card-title">보존·집계 정책</div><div class="timeline"><div class="event"><b>Raw 데이터</b><p>30초~5분 수집 · 3개월 보존</p></div><div class="event"><b>1시간 통계 생성</b><p>매시 10분 · 평균/최대/최소/건수</p></div><div class="event"><b>일 통계 생성</b><p>매일 02:10 · 3년 보존</p></div><div class="event"><b>보존기간 경과 삭제</b><p>월 단위 파티션 정리 권장</p></div></div><div class="callout">CCTV 1,000대를 30초 주기로 모두 적재하면 데이터량이 급증합니다. 현재값·원본·집계 테이블을 분리합니다.</div></div></div>`)}
function faults(){const r=[['AL-260804-00831','심각','CCTV-0821','영상신호 없음','16:39:22','3분 01초','미확인'],['AL-260804-00830','경고','PBX-SW-03','에러패킷 4.12%','16:35:08','7분 15초','확인'],['AL-260804-00829','경고','TX-SW-012','포트 다운','16:31:14','11분 09초','임시조치'],['AL-260804-00828','주의','SCADA-GATE-17','응답 지연','16:25:47','16분 36초','확인'],['AL-260804-00827','주의','CCTV-0655','프레임 저하','16:21:05','21분 18초','미확인'],['AL-260804-00826','주의','PBX-CORE-01','메모리 68.5%','16:08:17','34분 06초','확인']];return layout('faults',`<div class="grid cols-4"><div class="card kpi"><div class="label">현재 장애</div><div class="value c-red">7</div><div class="sub">미확인 2</div></div><div class="card kpi"><div class="label">심각</div><div class="value c-red">1</div><div class="sub">즉시 조치</div></div><div class="card kpi"><div class="label">경고</div><div class="value c-yellow">2</div><div class="sub">담당자 통보</div></div><div class="card kpi"><div class="label">평균 확인시간</div><div class="value">2분 18초</div><div class="sub">오늘 기준</div></div><div class="card span-4"><div class="filter"><select class="input"><option>전체 등급</option></select><select class="input"><option>전체 시스템</option></select><select class="input"><option>미완료</option></select><input class="input wide" value="장비명 / 장애내용"><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>장애번호</th><th>등급</th><th>대상장비</th><th>장애내용</th><th>발생시각</th><th>경과시간</th><th>처리상태</th><th>장애판단</th><th>조치</th></tr>${r.map(x=>`<tr><td>${x[0]}</td><td>${chip(x[1],x[1]==='심각'?'bad':x[1]==='경고'?'warn':'')}</td><td><b>${x[2]}</b></td><td>${x[3]}</td><td>${x[4]}</td><td>${x[5]}</td><td>${x[6]}</td><td><select class="input" style="min-width:100px;height:28px"><option>상태장애</option></select></td><td>${btn('조치','sm primary')}</td></tr>`).join('')}</table></div></div>`,btn('일괄 확인')+btn('EMS 제어 설정'))}
function faultHistory(){return layout('faultHistory',`<div class="split"><div class="card"><div class="card-title">장애 처리 Timeline <small>AL-260804-00794</small></div><div class="timeline"><div class="event"><b>장애 발생</b><p>14:08:11 · CCTV-0721 연결 끊김</p></div><div class="event"><b>운영자 확인</b><p>14:09:02 · 김관리</p></div><div class="event"><b>임시조치</b><p>14:12:44 · VMS 채널 재시작</p></div><div class="event"><b>상태 복구</b><p>14:18:05 · 자동 감지</p></div><div class="event"><b>완료조치</b><p>14:22:31 · 네트워크 케이블 교체 예정</p></div></div><div class="callout">임시조치·완료조치는 별도 이력으로 누적되며 수정 전후 값과 작업자를 기록합니다.</div></div><div class="card"><div class="filter"><input class="input" value="2026-08-01"><input class="input" value="2026-08-04"><select class="input"><option>전체 시스템</option></select><select class="input"><option>전체 처리상태</option></select><div class="spacer"></div>${btn('검색','primary')}${btn('Excel')}</div><table><tr><th>장애번호</th><th>등급</th><th>장비</th><th>장애내용</th><th>발생일시</th><th>복구일시</th><th>장애시간</th><th>완료조치</th><th>담당자</th></tr><tr><td>AL-260804-00794</td><td>${chip('경고','warn')}</td><td>CCTV-0721</td><td>연결 끊김</td><td>14:08:11</td><td>14:18:05</td><td>9분 54초</td><td>케이블 점검 예정</td><td>김관리</td></tr><tr><td>AL-260804-00781</td><td>${chip('주의')}</td><td>PBX-SW-11</td><td>응답 지연</td><td>12:40:17</td><td>12:44:31</td><td>4분 14초</td><td>모듈 재시작</td><td>이운영</td></tr><tr><td>AL-260804-00752</td><td>${chip('심각','bad')}</td><td>SCADA-CORE</td><td>연계 중단</td><td>09:12:05</td><td>09:28:18</td><td>16분 13초</td><td>세션 재연결</td><td>박담당</td></tr><tr><td>AL-260804-00721</td><td>${chip('경고','warn')}</td><td>TX-SW-002</td><td>포트 다운</td><td>07:31:48</td><td>07:39:02</td><td>7분 14초</td><td>광모듈 교체</td><td>김관리</td></tr></table><div class="pager"><div class="page">‹</div><div class="page on">1</div><div class="page">2</div><div class="page">3</div><div class="page">›</div></div></div></div>`,btn('장애발생 조치보고서')+btn('완료조치 등록','primary'))}
function exceptions(){return layout('exceptions',`<div class="split"><div class="card"><div class="card-title">장애 예외 그룹</div><div class="tree"><div class="row sel">정기점검 장비 <span class="count">48</span></div><div class="row">공항1터미널 CCTV <span class="count">22</span></div><div class="row">교환기 시험장비 <span class="count">8</span></div><div class="row">SCADA 공사구간 <span class="count">12</span></div><div class="row">전송설비 예비장비 <span class="count">6</span></div></div>${btn('그룹 추가','primary')}${btn('그룹 수정')}</div><div class="card"><div class="card-title">예외시간 설정 <small>정기점검 장비</small></div><div class="form-grid"><div class="label">설정명</div><div class="field">8월 정기점검</div><div class="label">사용여부</div><div class="field">사용</div><div class="label">시작일시</div><div class="field">2026-08-09 01:00</div><div class="label">종료일시</div><div class="field">2026-08-09 04:00</div><div class="label">반복구분</div><div class="field">반복 없음</div><div class="label">예외등급</div><div class="field">주의·경고 (심각 제외)</div><div class="label">사유</div><div class="field span-3">UPS 점검으로 인한 계획 정지</div></div><div class="card-title" style="margin-top:18px">포함 장비 <small>48건</small></div><table><tr><th>장비명</th><th>시스템</th><th>역사</th><th>예외대상 지표</th><th>삭제</th></tr><tr><td>CCTV-0811</td><td>영상감시</td><td>공항화물청사</td><td>PING·영상신호</td><td>${btn('삭제','sm danger')}</td></tr><tr><td>PBX-SW-08</td><td>전화교환</td><td>인천공항1터미널</td><td>PING·포트상태</td><td>${btn('삭제','sm danger')}</td></tr><tr><td>SCADA-GATE-22</td><td>SCADA 보안</td><td>검암</td><td>연결상태</td><td>${btn('삭제','sm danger')}</td></tr></table></div></div>`,btn('예외 일정 등록','primary'))}
function faultTypes(){return layout('faultTypes',`<div class="card"><div class="filter"><select class="input"><option>전체 시스템</option></select><select class="input"><option>전체 등급</option></select><input class="input wide" value="장애유형명 / 이벤트코드"><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>이벤트코드</th><th>장애유형명</th><th>시스템</th><th>기본등급</th><th>판단기준</th><th>자동종료</th><th>SMS</th><th>사용여부</th><th>수정</th></tr><tr><td>VMS-001</td><td>영상신호 없음</td><td>영상감시</td><td>${chip('심각','bad')}</td><td>3회 연속 신호 없음</td><td>Y</td><td>Y</td><td>${chip('사용')}</td><td>${btn('수정','sm')}</td></tr><tr><td>PBX-104</td><td>에러패킷 임계치 초과</td><td>전화교환</td><td>${chip('경고','warn')}</td><td>3% 초과 1분</td><td>Y</td><td>Y</td><td>${chip('사용')}</td><td>${btn('수정','sm')}</td></tr><tr><td>SCADA-012</td><td>출입문 비정상 개방</td><td>SCADA 보안</td><td>${chip('심각','bad')}</td><td>승인 이벤트 없음</td><td>N</td><td>Y</td><td>${chip('사용')}</td><td>${btn('수정','sm')}</td></tr><tr><td>NET-021</td><td>PING 응답 없음</td><td>공통</td><td>${chip('경고','warn')}</td><td>3회 연속 실패</td><td>Y</td><td>N</td><td>${chip('사용')}</td><td>${btn('수정','sm')}</td></tr><tr><td>SYS-004</td><td>CPU 임계치 초과</td><td>공통</td><td>${chip('주의')}</td><td>70% 초과 5분</td><td>Y</td><td>N</td><td>${chip('사용')}</td><td>${btn('수정','sm')}</td></tr></table><div class="callout" style="margin-top:18px">EMS 연동 시 미등록 이벤트코드는 자동으로 후보 등록하고, 운영자가 등급·판단기준·전송여부를 확정합니다.</div></div>`,btn('장애유형 등록','primary'))}
function reports(){return layout('reports',`<div class="grid cols-3"><div class="card"><div class="card-title">보고서 조건</div><div class="form-grid" style="grid-template-columns:110px 1fr"><div class="label">보고서 종류</div><div class="field">장애현황 보고서</div><div class="label">조회기간</div><div class="field">2026-07-01 ~ 2026-07-31</div><div class="label">시스템</div><div class="field">전체</div><div class="label">장애등급</div><div class="field">전체</div><div class="label">집계단위</div><div class="field">주간</div></div><div style="margin-top:14px">${btn('미리보기','primary')}${btn('Excel 저장')}${btn('PDF 출력')}</div></div><div class="card span-2"><div class="card-title">2026년 7월 장애현황 보고서 <small>전체 시스템</small></div><div class="grid cols-4"><div class="card kpi"><div class="label">발생 장애</div><div class="value">284</div></div><div class="card kpi"><div class="label">서비스 장애</div><div class="value c-red">12</div></div><div class="card kpi"><div class="label">평균 복구시간</div><div class="value">8분 42초</div></div><div class="card kpi"><div class="label">조치 완료율</div><div class="value c-green">98.6%</div></div></div><div class="linechart" style="height:250px;margin-top:18px"><svg viewBox="0 0 1000 250"><polyline points="0,190 100,160 200,184 300,112 400,135 500,92 600,120 700,74 800,96 900,55 1000,82" fill="none" stroke="#3bd4df" stroke-width="4"/><polyline points="0,210 100,205 200,196 300,190 400,185 500,170 600,165 700,154 800,150 900,142 1000,138" fill="none" stroke="#ffcb65" stroke-width="3"/></svg></div><table><tr><th>시스템</th><th class="right">발생</th><th class="right">심각</th><th class="right">평균복구</th><th class="right">완료율</th></tr><tr><td>영상감시</td><td class="right">118</td><td class="right c-red">7</td><td class="right">11분 12초</td><td class="right">97.5%</td></tr><tr><td>전화교환</td><td class="right">64</td><td class="right">2</td><td class="right">7분 05초</td><td class="right">98.4%</td></tr><tr><td>SCADA 보안</td><td class="right">43</td><td class="right">1</td><td class="right">8분 31초</td><td class="right">100%</td></tr></table></div></div>`)}
const users=[['admin','시스템관리자','AREX 정보통신팀','시스템 관리자','정상','16:31:20'],['kim01','김관리','AREX 정보통신팀','운영 관리자','정상','15:58:42'],['lee02','이운영','AREX 관제팀','운영자','정상','14:22:08'],['park03','박담당','CCTV 유지보수사','설비 담당자','정상','13:17:55'],['vendor04','최지원','교환기 구축사','조회 사용자','잠금','2026-08-01']];
function usersScreen(){return layout('users',`<div class="card"><div class="filter"><select class="input"><option>전체 소속</option></select><select class="input"><option>전체 권한</option></select><select class="input"><option>전체 상태</option></select><input class="input wide" value="아이디 / 사용자명"><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>사용자 아이디</th><th>사용자명</th><th>소속</th><th>권한</th><th>전화번호</th><th>상태</th><th>최근 로그인</th><th>관리</th></tr>${users.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>010-12**-56**</td><td>${chip(x[4],x[4]==='잠금'?'bad':'')}</td><td>${x[5]}</td><td>${btn('수정','sm')}</td></tr>`).join('')}</table><div class="pager"><div class="page on">1</div><div class="page">2</div><div class="page">3</div></div></div>`,btn('사용자 등록','primary'))}
function auth(){const menus=['통합 대시보드','역사·선로 현황','연동시스템 관리','장비 관리','교환기 관리','CCTV 상태관리','CCTV 영상관리','SCADA 출입보안','연동주기 관리','임계치 관리','실시간 장애','장애이력·조치'];return layout('auth',`<div class="split"><div class="card"><div class="card-title">권한 목록</div><div class="tree"><div class="row sel">시스템 관리자 <span class="count">1명</span></div><div class="row">운영 관리자 <span class="count">4명</span></div><div class="row">운영자 <span class="count">12명</span></div><div class="row">설비 담당자 <span class="count">18명</span></div><div class="row">조회 사용자 <span class="count">26명</span></div></div>${btn('권한 추가','primary')}${btn('권한명 수정')}</div><div class="card"><div class="card-title">메뉴·기능 권한 <small>시스템 관리자</small></div><table class="matrix"><tr><th>메뉴</th><th>목록</th><th>상세</th><th>등록</th><th>수정</th><th>삭제</th><th>제어</th></tr>${menus.map((x,i)=>`<tr><td>${x}</td>${[1,1,i===0?0:1,i===0?0:1,i>1?1:0,i>=4&&i<=7?1:0].map(v=>`<td><span class="check ${v?'on':''}"></span></td>`).join('')}</tr>`).join('')}</table><div class="callout" style="margin-top:14px">상세 권한이 없으면 목록에서 항목 클릭을 제한합니다. 제어 권한은 EMS 제어·CCTV PTZ 등 원격조작 기능에만 별도로 적용합니다.</div></div></div>`,btn('저장','primary'))}
function applications(){return layout('applications',`<div class="card"><div class="filter"><select class="input"><option>승인 대기</option></select><input class="input wide" value="신청자명 / 소속"><div class="spacer"></div>${btn('검색','primary')}</div><table><tr><th>신청번호</th><th>신청자</th><th>소속</th><th>요청권한</th><th>신청사유</th><th>신청일시</th><th>상태</th><th>처리</th></tr><tr><td>APLY-20260804-012</td><td>정현우</td><td>CCTV 유지보수사</td><td>설비 담당자</td><td>CCTV 점검 및 장애조치</td><td>2026-08-04 15:11</td><td>${chip('승인대기','warn')}</td><td>${btn('승인','sm primary')} ${btn('반려','sm danger')}</td></tr><tr><td>APLY-20260804-011</td><td>오민지</td><td>AREX 관제팀</td><td>운영자</td><td>신규 관제업무 담당</td><td>2026-08-04 13:42</td><td>${chip('승인대기','warn')}</td><td>${btn('승인','sm primary')} ${btn('반려','sm danger')}</td></tr><tr><td>APLY-20260803-010</td><td>윤지원</td><td>교환기 구축사</td><td>조회 사용자</td><td>정기점검 보고서 확인</td><td>2026-08-03 17:02</td><td>${chip('승인완료')}</td><td>${btn('상세','sm')}</td></tr></table></div>`)}
function notify(){return layout('notify',`<div class="split"><div class="card"><div class="card-title">SMS 전송그룹</div><div class="tree"><div class="row sel">심각 장애 즉시통보 <span class="count">8명</span></div><div class="row">CCTV 장애 담당 <span class="count">5명</span></div><div class="row">교환기 장애 담당 <span class="count">4명</span></div><div class="row">SCADA 장애 담당 <span class="count">6명</span></div><div class="row">야간 당직자 <span class="count">3명</span></div></div>${btn('그룹 추가','primary')}</div><div class="card"><div class="card-title">심각 장애 즉시통보 <small>사용 중</small></div><div class="form-grid"><div class="label">전송등급</div><div class="field">심각</div><div class="label">전송시간</div><div class="field">24시간</div><div class="label">재전송</div><div class="field">미확인 시 5분 후</div><div class="label">최대횟수</div><div class="field">3회</div></div><div class="card-title" style="margin-top:18px">수신 대상</div><table><tr><th>사용자명</th><th>소속</th><th>휴대전화번호</th><th>수신여부</th><th>삭제</th></tr>${users.slice(0,4).map(x=>`<tr><td>${x[1]}</td><td>${x[2]}</td><td>010-12**-56**</td><td>${chip('수신')}</td><td>${btn('삭제','sm danger')}</td></tr>`).join('')}</table></div></div>`,btn('SMS 전송이력')+btn('저장','primary'))}
function settings(){return layout('settings',`<div class="grid cols-2"><div class="card"><div class="card-title">UI 설정</div><div class="form-grid"><div class="label">목록 기본 행수</div><div class="field">20행</div><div class="label">대시보드 갱신주기</div><div class="field">10초</div><div class="label">비밀번호 변경알림</div><div class="field">90일</div><div class="label">장애 팝업</div><div class="field">경고 이상</div><div class="label">사운드 알림</div><div class="field">심각 등급</div><div class="label">55인치 표출모드</div><div class="field">사용</div></div><div class="card-title" style="margin-top:18px">이벤트 등급 색상</div><table><tr><th>등급</th><th>표시명</th><th>색상</th><th>사용</th></tr><tr><td>1</td><td>정상</td><td><span style="color:#45df9a">■ #45DF9A</span></td><td>Y</td></tr><tr><td>2</td><td>주의</td><td><span style="color:#ffcc66">■ #FFCC66</span></td><td>Y</td></tr><tr><td>3</td><td>경고</td><td><span style="color:#ff9955">■ #FF9955</span></td><td>Y</td></tr><tr><td>4</td><td>심각</td><td><span style="color:#ff7389">■ #FF7389</span></td><td>Y</td></tr></table></div><div class="card"><div class="card-title">공통코드 관리</div><div class="split" style="grid-template-columns:260px 1fr"><div class="tree"><div class="row sel">장애등급 <span class="count">4</span></div><div class="row">장비구분 <span class="count">12</span></div><div class="row">시스템구분 <span class="count">5</span></div><div class="row">처리상태 <span class="count">6</span></div><div class="row">프로토콜 <span class="count">8</span></div><div class="row">수집데이터구분 <span class="count">4</span></div></div><div><table><tr><th>코드</th><th>코드명</th><th>순서</th><th>사용</th></tr><tr><td>NORMAL</td><td>정상</td><td>1</td><td>Y</td></tr><tr><td>CAUTION</td><td>주의</td><td>2</td><td>Y</td></tr><tr><td>WARNING</td><td>경고</td><td>3</td><td>Y</td></tr><tr><td>CRITICAL</td><td>심각</td><td>4</td><td>Y</td></tr></table>${btn('상세코드 추가','primary')}</div></div></div></div>`,btn('설정 저장','primary'))}
function logs(){return layout('logs',`<div class="card"><div class="filter"><input class="input" value="2026-08-04"><input class="input" value="2026-08-04"><select class="input"><option>전체 메뉴</option></select><select class="input"><option>전체 작업</option></select><input class="input wide" value="사용자명 / IP"><div class="spacer"></div>${btn('검색','primary')}${btn('Excel')}</div><table><tr><th>로그일련번호</th><th>작업일시</th><th>사용자</th><th>접속IP</th><th>메뉴</th><th>작업구분</th><th>대상</th><th>결과</th><th>상세</th></tr><tr><td>LOG-892144</td><td>16:41:12</td><td>김관리</td><td>10.10.1.25</td><td>실시간 장애</td><td>임시조치 등록</td><td>AL-260804-00829</td><td>${chip('성공')}</td><td>${btn('보기','sm')}</td></tr><tr><td>LOG-892143</td><td>16:39:40</td><td>시스템관리자</td><td>10.10.1.11</td><td>사용자 계정</td><td>로그인</td><td>admin</td><td>${chip('성공')}</td><td>${btn('보기','sm')}</td></tr><tr><td>LOG-892142</td><td>16:35:31</td><td>이운영</td><td>10.10.1.32</td><td>장애이력·조치</td><td>상세조회</td><td>AL-260804-00794</td><td>${chip('성공')}</td><td>${btn('보기','sm')}</td></tr><tr><td>LOG-892141</td><td>16:31:02</td><td>vendor04</td><td>10.10.5.44</td><td>로그인</td><td>인증</td><td>vendor04</td><td>${chip('실패','bad')}</td><td>${btn('보기','sm')}</td></tr><tr><td>LOG-892140</td><td>16:28:18</td><td>박담당</td><td>10.10.2.18</td><td>CCTV 상태관리</td><td>목록조회</td><td>검암</td><td>${chip('성공')}</td><td>${btn('보기','sm')}</td></tr></table></div>`)}

function escapeHtml(value){return String(value==null?'':value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function hasPermission(screen,property){const p=PERMISSIONS[screen];return !!p&&p[property||'listAuthrtYn']==='Y'}
function permissionButton(screen,property,label,classes,handler){return hasPermission(screen,property)?`<button class="btn ${classes||''}" onclick="${handler}">${label}</button>`:''}
async function api(path,options={}){
  const headers=Object.assign({'X-Requested-With':'XMLHttpRequest'},options.headers||{});
  if(options.method&&options.method.toUpperCase()!=='GET')headers['X-CSRF-TOKEN']=CSRF_TOKEN;
  const response=await fetch(CONTEXT_PATH+path,Object.assign({},options,{headers}));
  let json;try{json=await response.json()}catch(e){json={success:false,message:'서버 응답을 해석하지 못했습니다.'}}
  if(response.status===401){location.replace(CONTEXT_PATH+'/login/login.do');throw new Error('로그인이 필요합니다.')}
  if(!response.ok||json.success===false)throw new Error(json.message||'요청 처리에 실패했습니다.');
  return json.data;
}
function showToast(message,bad){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast'+(bad?' bad':'');el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2800)}
function showModal(html){const el=document.createElement('div');el.className='modal-backdrop';el.id='modalBackdrop';el.innerHTML=`<div class="modal-panel">${html}</div>`;el.addEventListener('click',e=>{if(e.target===el)closeModal()});document.body.appendChild(el)}
function closeModal(){const el=document.getElementById('modalBackdrop');if(el)el.remove()}
function formatDate(value){return value?String(value).replace('T',' ').substring(0,19):'-'}

usersScreen=function(){
  const actions=permissionButton('users','regAuthrtYn','사용자 등록','primary','openUserModal()');
  return layout('users',`<div class="card"><div class="filter"><select id="userAuthFilter" class="input"><option value="">전체 권한</option></select><select id="userStatusFilter" class="input"><option value="">전체 상태</option><option>정상</option><option>잠금</option><option>중지</option></select><input id="userKeyword" class="input wide" placeholder="아이디 / 사용자명 / 소속"><div class="spacer"></div><button class="btn primary" onclick="loadUsers()">검색</button></div><div class="card-title">사용자 목록 <small id="userCount">조회 중</small></div><table><thead><tr><th>사용자 아이디</th><th>사용자명</th><th>소속</th><th>부서</th><th>권한</th><th>전화번호</th><th>상태</th><th>최근 로그인</th><th>관리</th></tr></thead><tbody id="userRows"><tr><td class="empty-row" colspan="9">조회 중입니다.</td></tr></tbody></table></div>`,actions)
};

async function loadAuthOptions(){
  const list=await api('/auth/options.ajax');
  const select=document.getElementById('userAuthFilter');
  if(select){const current=select.value;select.innerHTML='<option value="">전체 권한</option>'+list.map(a=>`<option value="${a.authrtSn}">${escapeHtml(a.authrtNm)}</option>`).join('');select.value=current}
  return list;
}
async function loadUsers(){
  try{
    const params=new URLSearchParams();
    const auth=document.getElementById('userAuthFilter'),status=document.getElementById('userStatusFilter'),keyword=document.getElementById('userKeyword');
    if(auth&&auth.value)params.set('authrtSn',auth.value);if(status&&status.value)params.set('userSttsNm',status.value);if(keyword&&keyword.value.trim())params.set('searchKeyword',keyword.value.trim());
    const list=await api('/user/list.ajax?'+params.toString());
    document.getElementById('userCount').textContent=`총 ${list.length}건`;
    document.getElementById('userRows').innerHTML=list.length?list.map(u=>`<tr><td><b>${escapeHtml(u.userId)}</b></td><td>${escapeHtml(u.userNm)}</td><td>${escapeHtml(u.ogdpBzentyNm||'-')}</td><td>${escapeHtml(u.deptNm||'-')}</td><td>${escapeHtml(u.authrtNm||'-')}</td><td>${escapeHtml(u.telno||'-')}</td><td>${chip(escapeHtml(u.userSttsNm),u.userSttsNm==='잠금'?'bad':'')}</td><td>${formatDate(u.lastLgnDt)}</td><td>${hasPermission('users','mdfcnAuthrtYn')?`<button class="btn sm" onclick="openUserModal(${u.userSn})">수정</button> ${u.userSttsNm==='잠금'?`<button class="btn sm" onclick="unlockUser(${u.userSn})">잠금해제</button>`:''}`:''}</td></tr>`).join(''):'<tr><td class="empty-row" colspan="9">조회 결과가 없습니다.</td></tr>';
  }catch(e){showToast(e.message,true)}
}
async function openUserModal(userSn){
  try{
    USER_ID_CHECKED=false;
    const [authList,user]=await Promise.all([loadAuthOptions(),userSn?api('/user/detail.ajax?userSn='+userSn):Promise.resolve({useYn:'Y',userSttsNm:'정상'})]);
    const edit=!!userSn;
    showModal(`<div class="modal-head"><h2>${edit?'사용자 수정':'사용자 등록'}</h2><button class="modal-close" onclick="closeModal()">×</button></div><form id="userForm"><input type="hidden" name="userSn" value="${user.userSn||''}"><div class="edit-form"><label>사용자 아이디 *</label><div><input class="form-control" name="userId" id="modalUserId" value="${escapeHtml(user.userId||'')}" ${edit?'readonly':''} required>${edit?'':'<button type="button" class="btn sm" style="margin-top:6px" onclick="checkUserId()">중복 확인</button><span id="idCheckResult" class="form-help"></span>'}</div><label>사용자명 *</label><div><input class="form-control" name="userNm" value="${escapeHtml(user.userNm||'')}" required></div><label>소속업체</label><div><input class="form-control" name="ogdpBzentyNm" value="${escapeHtml(user.ogdpBzentyNm||'')}"></div><label>부서</label><div><input class="form-control" name="deptNm" value="${escapeHtml(user.deptNm||'')}"></div><label>전화번호</label><div><input class="form-control" name="telno" value="${escapeHtml(user.telno||'')}" placeholder="하이픈 없이 숫자만"></div><label>이메일</label><div><input class="form-control" name="emlAddr" type="email" value="${escapeHtml(user.emlAddr||'')}"></div><label>권한 *</label><div><select class="form-control" name="authrtSn" required>${authList.map(a=>`<option value="${a.authrtSn}" ${String(a.authrtSn)===String(user.authrtSn)?'selected':''}>${escapeHtml(a.authrtNm)}</option>`).join('')}</select></div><label>계정 상태</label><div><select class="form-control" name="userSttsNm">${['정상','잠금','중지'].map(s=>`<option ${s===user.userSttsNm?'selected':''}>${s}</option>`).join('')}</select><input type="hidden" name="useYn" value="${user.useYn||'Y'}"></div><label>${edit?'새 비밀번호':'초기 비밀번호 *'}</label><div><input class="form-control" name="password" type="password" ${edit?'':'required'}><span class="form-help">영문·숫자·특수문자 포함 8~20자</span></div><label>비밀번호 확인</label><div><input class="form-control" name="passwordConfirm" type="password" ${edit?'':'required'}></div></div><div class="modal-actions">${edit&&hasPermission('users','delAuthrtYn')?`<button type="button" class="btn danger" onclick="deleteUser(${userSn})">삭제</button>`:''}<button type="button" class="btn" onclick="closeModal()">취소</button><button type="submit" class="btn primary">저장</button></div></form>`);
    document.getElementById('userForm').addEventListener('submit',saveUser);
    if(!edit)document.getElementById('modalUserId').addEventListener('input',()=>{USER_ID_CHECKED=false;const result=document.getElementById('idCheckResult');if(result)result.textContent=''});
  }catch(e){showToast(e.message,true)}
}
let USER_ID_CHECKED=false;
async function checkUserId(){try{const id=document.getElementById('modalUserId').value.trim();const data=await api('/user/idCheck.ajax?userId='+encodeURIComponent(id));USER_ID_CHECKED=data.available;document.getElementById('idCheckResult').textContent=data.available?'사용 가능한 아이디입니다.':'이미 사용 중인 아이디입니다.'}catch(e){showToast(e.message,true)}}
async function saveUser(e){e.preventDefault();const form=e.target,edit=!!form.querySelector('[name=userSn]').value;if(!edit&&!USER_ID_CHECKED){showToast('아이디 중복 확인을 해주세요.',true);return}try{await api(edit?'/user/update.ajax':'/user/insert.ajax',{method:'POST',body:new URLSearchParams(new FormData(form))});closeModal();showToast(edit?'사용자 정보를 수정했습니다.':'사용자를 등록했습니다.');await loadUsers()}catch(error){showToast(error.message,true)}}
async function deleteUser(userSn){if(!confirm('선택한 사용자를 삭제하시겠습니까?'))return;try{await api('/user/delete.ajax',{method:'POST',body:new URLSearchParams({userSn})});closeModal();showToast('사용자를 삭제했습니다.');await loadUsers()}catch(e){showToast(e.message,true)}}
async function unlockUser(userSn){if(!confirm('계정 잠금을 해제하시겠습니까?'))return;try{await api('/user/unlock.ajax',{method:'POST',body:new URLSearchParams({userSn})});showToast('계정 잠금을 해제했습니다.');await loadUsers()}catch(e){showToast(e.message,true)}}

auth=function(){
  const actions=permissionButton('auth','regAuthrtYn','권한 추가','primary','openAuthModal()');
  return layout('auth',`<div class="split"><div class="card"><div class="card-title">권한 목록</div><div class="tree" id="authRows"><div class="row">조회 중입니다.</div></div></div><div class="card" id="authDetail"><div class="empty-row">왼쪽에서 권한을 선택해 주세요.</div></div></div>`,actions)
};
let CURRENT_AUTH_SN=null;
let CURRENT_AUTH_DATA=null;
async function loadAuths(selected){
  try{const list=await api('/auth/list.ajax');const target=selected||CURRENT_AUTH_SN||(list[0]&&list[0].authrtSn);document.getElementById('authRows').innerHTML=list.length?list.map(a=>`<div class="row clickable ${String(a.authrtSn)===String(target)?'sel':''}" onclick="loadAuthDetail(${a.authrtSn})">${escapeHtml(a.authrtNm)} <span class="count">${a.userNocs||0}명</span></div>`).join(''):'<div class="row">등록된 권한이 없습니다.</div>';if(target)await loadAuthDetail(target,false)}catch(e){showToast(e.message,true)}
}
async function loadAuthDetail(authrtSn,reloadList=true){
  try{CURRENT_AUTH_SN=authrtSn;const a=await api('/auth/detail.ajax?authrtSn='+authrtSn);CURRENT_AUTH_DATA={authrtSn:a.authrtSn,authrtNm:a.authrtNm,authrtExpln:a.authrtExpln||''};if(reloadList){document.querySelectorAll('#authRows .row').forEach(x=>x.classList.remove('sel'));const rows=[...document.querySelectorAll('#authRows .row')];const row=rows.find(x=>x.getAttribute('onclick')&&x.getAttribute('onclick').includes('('+authrtSn+')'));if(row)row.classList.add('sel')}
    document.getElementById('authDetail').innerHTML=`<div class="card-title">메뉴·기능 권한 <small>${escapeHtml(a.authrtNm)}</small></div><div style="display:flex;gap:8px;margin-bottom:12px">${hasPermission('auth','mdfcnAuthrtYn')?`<button class="btn" onclick="openAuthModal(CURRENT_AUTH_DATA)">권한명 수정</button>`:''}${hasPermission('auth','delAuthrtYn')&&a.authrtSn!==1?`<button class="btn danger" onclick="deleteAuth(${a.authrtSn})">권한 삭제</button>`:''}</div><table class="matrix table-wide-xl"><thead><tr><th>메뉴</th><th>목록</th><th>상세</th><th>등록</th><th>수정</th><th>삭제</th><th>제어</th></tr></thead><tbody>${a.menuAuthList.map(m=>`<tr data-menu-sn="${m.menuSn}"><td>${escapeHtml(m.menuNm)}</td>${['listAuthrtYn','dtlAuthrtYn','regAuthrtYn','mdfcnAuthrtYn','delAuthrtYn','ctrlAuthrtYn'].map(k=>`<td><input class="perm-check" type="checkbox" data-key="${k}" ${m[k]==='Y'?'checked':''} ${!hasPermission('auth','mdfcnAuthrtYn')||a.authrtSn===1?'disabled':''}></td>`).join('')}</tr>`).join('')}</tbody></table><div class="callout" style="margin-top:14px">상세·등록·수정·삭제·제어 권한을 선택하면 목록 권한이 자동으로 포함됩니다. 시스템 관리자 권한은 보호됩니다.</div>${hasPermission('auth','mdfcnAuthrtYn')&&a.authrtSn!==1?'<div class="modal-actions"><button class="btn primary" onclick="savePermissions()">권한 저장</button></div>':''}`;enhanceTables(document.getElementById('authDetail'));
  }catch(e){showToast(e.message,true)}
}
function openAuthModal(authData){const a=authData||{};showModal(`<div class="modal-head"><h2>${a.authrtSn?'권한 수정':'권한 등록'}</h2><button class="modal-close" onclick="closeModal()">×</button></div><form id="authForm"><input type="hidden" name="authrtSn" value="${a.authrtSn||''}"><div class="edit-form"><label>권한명 *</label><div class="full"><input class="form-control" name="authrtNm" value="${escapeHtml(a.authrtNm||'')}" maxlength="100" required></div><label>권한 설명</label><div class="full"><input class="form-control" name="authrtExpln" value="${escapeHtml(a.authrtExpln||'')}" maxlength="4000"></div></div><input type="hidden" name="useYn" value="Y"><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">취소</button><button class="btn primary" type="submit">저장</button></div></form>`);document.getElementById('authForm').addEventListener('submit',saveAuth)}
async function saveAuth(e){e.preventDefault();const authrtSn=e.target.querySelector('[name=authrtSn]').value,edit=!!authrtSn;try{const data=await api(edit?'/auth/update.ajax':'/auth/insert.ajax',{method:'POST',body:new URLSearchParams(new FormData(e.target))});closeModal();showToast(edit?'권한을 수정했습니다.':'권한을 등록했습니다.');await loadAuths(edit?authrtSn:data.authrtSn)}catch(error){showToast(error.message,true)}}
async function deleteAuth(authrtSn){if(!confirm('선택한 권한을 삭제하시겠습니까?'))return;try{await api('/auth/delete.ajax',{method:'POST',body:new URLSearchParams({authrtSn})});CURRENT_AUTH_SN=null;showToast('권한을 삭제했습니다.');await loadAuths()}catch(e){showToast(e.message,true)}}
async function savePermissions(){const rows=[...document.querySelectorAll('#authDetail tbody tr')];const menuAuthList=rows.map(row=>{const item={menuSn:Number(row.dataset.menuSn)};row.querySelectorAll('input[data-key]').forEach(input=>item[input.dataset.key]=input.checked?'Y':'N');return item});try{await api('/auth/savePermissions.ajax',{method:'POST',headers:{'Content-Type':'application/json;charset=UTF-8'},body:JSON.stringify({authrtSn:CURRENT_AUTH_SN,menuAuthList})});showToast('메뉴·기능 권한을 저장했습니다.');await bootstrapPermissions(false);await loadAuthDetail(CURRENT_AUTH_SN)}catch(e){showToast(e.message,true)}}

/* 첨부 기획 시안 기반 공통 UI 및 설비 화면 */
Object.assign(S,{
  dashboard:{menu:'통합 대시보드',title:'통합망 관리시스템',desc:''},
  systems:{menu:'전송설비',title:'설비관리 > 전송설비',desc:''},
  equipment:{menu:'행선안내설비',title:'설비관리 > 행선안내설비',desc:''},
  switch:{menu:'전화교환설비',title:'설비관리 > 전화교환설비',desc:''},
  cctv:{menu:'영상감시설비(CCTV)',title:'설비관리 > 영상감시설비(CCTV)',desc:''},
  scada:{menu:'SCADA 출입보안설비',title:'설비관리 > SCADA 출입보안설비',desc:''}
});
NAV.splice(0,NAV.length,
  ['', ['통합 대시보드','역사·선로 현황']],
  ['설비관리',['전송설비','행선안내설비','SCADA 출입보안설비','전화교환설비','영상감시설비(CCTV)','CCTV 영상관리']],
  ['장애관리',['실시간 장애','장애이력·조치','장애 예외설정','장애유형 관리']],
  ['성능관리',['성능관리','연동주기 관리','임계치 관리','Raw 데이터 관리']],
  ['보고서',['장애·성능 보고서']],
  ['운영관리',['사용자 계정 설정','권한 관리','계정 신청 현황','알림·SMS 설정','작업로그 조회']],
  ['설정',['공통코드·UI 설정']]
);
Object.keys(MENU_KEY).forEach(key=>delete MENU_KEY[key]);
Object.entries(S).forEach(([key,value])=>MENU_KEY[value.menu]=key);

function navIcon(key){
  const icons={
    dashboard:'<path d="M4 11l8-7 8 7v9H5v-9"></path><path d="M9 20v-6h6v6"></path>',
    route:'<circle cx="6" cy="17" r="2"></circle><circle cx="18" cy="7" r="2"></circle><path d="M8 16c3-1 4-7 8-8"></path>',
    systems:'<path d="M4 7h16M4 12h16M4 17h16"></path><circle cx="7" cy="7" r="1"></circle>',
    equipment:'<rect x="5" y="4" width="14" height="16" rx="2"></rect><path d="M8 8h8M8 12h8"></path>',
    switch:'<path d="M4 7h16v10H4z"></path><path d="M8 10h2m2 0h2m2 0h1"></path>',
    cctv:'<path d="M4 8h11l4 4-4 4H4z"></path><circle cx="9" cy="12" r="2"></circle>',
    video:'<rect x="3" y="5" width="18" height="14" rx="2"></rect><path d="M10 9l5 3-5 3z"></path>',
    scada:'<path d="M5 20V9m7 11V4m7 16v-7"></path><path d="M3 20h18"></path>',
    faults:'<path d="M12 3l9 17H3z"></path><path d="M12 9v4m0 3h.01"></path>',
    performance:'<circle cx="12" cy="12" r="8"></circle><path d="M12 12l4-4"></path>',
    reports:'<path d="M6 3h9l3 3v15H6z"></path><path d="M9 12h6m-6 4h6"></path>',
    users:'<circle cx="9" cy="8" r="3"></circle><path d="M3 20c.4-4 2.5-6 6-6s5.6 2 6 6"></path>',
    settings:'<circle cx="12" cy="12" r="3"></circle><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"></path>'
  };
  const generic='<circle cx="12" cy="12" r="8"></circle><path d="M8 12h8M12 8v8"></path>';
  return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[key]||icons[key==='faultHistory'||key==='exceptions'||key==='faultTypes'?'faults':key==='cycle'||key==='threshold'||key==='raw'?'performance':key==='auth'||key==='applications'||key==='notify'||key==='logs'?'users':key]||generic}</svg>`;
}

function headerDateTime(){
  const now=new Date();
  const date=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).format(now);
  return `${date} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;
}

function modernSidebar(active){return `<aside class="sidebar"><div class="brand"><div class="logo">AREX</div><div class="brand-copy"><b>AREX TNMS</b></div></div><div class="nav">${NAV.map(([group,items])=>`${group?`<div class="nav-group">${group}</div>`:''}${items.map(name=>{const key=MENU_KEY[name]||'';const allowed=hasPermission(key,'listAuthrtYn');return `<div class="nav-item ${name===active?'active':''} ${allowed?'':'denied'}" data-key="${key}" title="${allowed?'':'접근 권한 없음'}"><i class="dot">${navIcon(key)}</i>${name}</div>`}).join('')}`).join('')}</div><div class="side-footer"><button class="side-collapse" type="button">← 메뉴 접기</button></div></aside>`}

function modernLayout(key,body,actions=''){
  const s=S[key],facility=['systems','equipment','switch','cctv','scada'].includes(key),dashboardPage=key==='dashboard';
  const heading=dashboardPage||facility?'':`<div class="heading"><div><h1>${s.title}</h1><p>${s.desc||''}</p></div><div class="actions">${actions}</div></div>`;
  return `<div class="app">${modernSidebar(s.menu)}<main class="main"><header class="topbar"><div class="page-title">${s.title}</div><div class="top-right"><span class="header-icon" title="알림"><svg viewBox="0 0 24 24"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5z"></path><path d="M10 20h4"></path></svg><em>12</em></span><div class="user"><b>${escapeHtml(CURRENT_USER.userNm||CURRENT_USER.userId||'운영자')}</b></div><span class="header-divider"></span><span class="header-clock">${headerDateTime()}</span><span class="fullscreen-icon" onclick="toggleFullscreen()" title="전체화면"></span><a class="logout" href="${CONTEXT_PATH}/login/logout.do" title="로그아웃">로그아웃</a></div></header><section class="content">${heading}${facility&&actions?`<div class="actions" style="margin-bottom:10px">${actions}</div>`:''}${body}</section></main></div>`;
}
function toggleFullscreen(){if(!document.fullscreenElement){document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen()}else{document.exitFullscreen&&document.exitFullscreen()}}

function rankRows(memory){return ['인천공항2터미널 SCADA','마곡나루 SCADA','김포공항 SCADA','청라국제도시 SCADA','영종역 SCADA'].map((name,i)=>`<div class="rank-row ${memory?'memory':''}"><span class="rank-no">${i+1}</span><span>${name}</span><span class="rank-bar"><i style="width:${memory?88-i*8:82-i*10}%"></i></span><b>${memory?(75.5-i*6.2).toFixed(1):(68.4-i*8.1).toFixed(1)}</b></div>`).join('')}
function circleStations(){const stations=[['104','디지털미디어시티',49.92,20.48,''],['105','마곡나루',61.32,22.44,''],['106','김포공항',71.11,27.71,'selected'],['108','계양',78.49,35.99,''],['109','검암',82.34,46.23,'warn'],['110','청라국제도시',82.34,56.93,''],['111','검암오류',78.49,67.02,'below'],['112','청라SSP',71.11,75.30,'below'],['114','영종하늘도시',61.32,80.57,'below'],['115','기지SS',49.92,82.53,'below'],['116','차량기지',38.68,80.57,'below'],['118','인천공항1터미널',28.73,75.30,'below'],['117','공항화물청사',21.19,67.02,'below'],['119','운서',17.50,56.93,'warn'],['121','인천공항2터미널',17.50,46.23,''],['101','서울역',21.19,35.99,''],['102','공덕',28.73,27.71,''],['103','홍대입구',38.68,22.44,'']];return stations.map(s=>`<div class="center-station ${s[4]}" style="left:${s[2]}%;top:${s[3]}%"><span class="center-station-info"><b class="center-station-code">${s[0]}</b>${s[1]}</span></div>`).join('')}
function systemSummaryRows(){return [['전송설비','정상',''],['행선안내설비','정상',''],['SCADA 출입보안설비','장애','bad'],['전화교환설비','정상',''],['영상감시설비(CCTV)','주의','warn']].map((x,i)=>`<div class="system-summary-row ${x[2]}"><span class="sys-icon">${i+1}</span><span><b>${x[0]}</b><small>${['Network','PIS','SCADA','Telephone','CCTV'][i]} System</small></span><strong>${x[1]}</strong><b>${i===2||i===4?'1건':'0건'}</b></div>`).join('')}

function dashboardOne(){return `<section class="dashboard-slide active" data-slide="0"><div class="dash-view-one"><aside class="dash-panel"><h3>현재 장애 현황</h3><div class="severity-list"><div class="severity-item bad"><span class="severity-mark">▲</span><b>긴급</b><strong>0</strong></div><div class="severity-item warn"><span class="severity-mark">◆</span><b>높음</b><strong>0</strong></div><div class="severity-item warn"><span class="severity-mark">!</span><b>낮음</b><strong>0</strong></div><div class="severity-item"><span class="severity-mark">●</span><b>경고</b><strong>0</strong></div><div class="severity-item"><span class="severity-mark">i</span><b>정보</b><strong>0</strong></div></div><div class="side-rank"><h4>[ CPU TOP 5 ]</h4>${rankRows(false)}</div><div class="side-rank"><h4>[ Memory TOP 5 ]</h4>${rankRows(true)}</div></aside><section class="dash-panel circle-board center-panel"><div class="center-panel-canvas"><div class="center-panel-head"><h3>전체 역사 / 노선 현황 (21개 역사)</h3><div class="center-top-legend"><span><i class="center-dot red"></i>긴급</span><span><i class="center-dot orange"></i>높음</span><span><i class="center-dot yellow"></i>낮음</span><span><i class="center-dot blue"></i>경고</span><span><i class="center-dot gray"></i>정보</span></div></div><div class="center-view-buttons"><button class="center-view-btn" type="button"><i></i>전체보기</button><button class="center-view-btn" type="button">▦ &nbsp; 범례</button></div><div class="center-route-ring"></div><img class="center-art" src="${CONTEXT_PATH}/images/tnms/dashboard-circle-center.png" alt="AREX 공항철도 일러스트"><div class="center-stations">${circleStations()}</div><div class="center-bottom-legend"><span><i class="center-dot red"></i>긴급</span><span><i class="center-dot orange"></i>높음</span><span><i class="center-dot yellow"></i>낮음</span><span><i class="center-dot blue"></i>경고</span><span><i class="center-dot gray"></i>정보</span></div></div></section><aside class="dash-panel"><h3>선택 역사 정보</h3><div class="selected-station"><h3>김포공항역 <small>(106)</small></h3><small>Gimpo Int'l Airport</small><p>장애 1건　/　주의 1건　/　정상 3건</p></div><div class="system-summary">${systemSummaryRows()}</div><div class="fault-mini"><h3>주요 장애 / 주의 현황</h3><div class="fault-mini-item"><b>▲ SCADA 출입보안설비</b><p>컨트롤러 통신 장애　10:28 발생</p></div><div class="fault-mini-item warn"><b>● 영상감시설비(CCTV)</b><p>NVR CPU 임계치 초과　10:25 발생</p></div></div></aside></div></section>`}

function dashboardSystemCards(){return [['△','CCTV'],['□','교환기'],['▥','SCADA'],['▣','행선안내'],['△','전송']].map(x=>`<div class="dash-system-card"><span class="sys-symbol">${x[0]}</span><span><b>${x[1]}</b><strong>000</strong></span><small>긴급 00</small></div>`).join('')}
function dashboardTwo(){return `<section class="dashboard-slide" data-slide="1"><div class="dash-system-cards">${dashboardSystemCards()}</div><div class="dash-panel map-dashboard"><div class="map-dashboard-head"><h3>공항철도 노선 · 역사 현황 지도</h3><div class="circle-legend"><span><i></i>정상</span><span><i class="orange"></i>주의</span><span><i class="red"></i>장애</span><span><i class="gray"></i>통신 단절</span></div></div><div class="map-board" role="img" aria-label="공항철도 노선과 역사 상태 지도"></div></div><div class="dash-bottom"><div class="dash-mini-chart"><h4>시간대별 발생 분포 (전체)</h4><div class="heat-grid">${Array.from({length:32},(_,i)=>`<i style="opacity:${.45+(i%5)*.12}"></i>`).join('')}</div></div><div class="dash-mini-chart mini-donut-row"><div><h4>장애 유형 분포</h4><div class="mini-donut"></div></div><div class="cause-ranks"><b>주요 장애 원인 TOP 3</b><div><span>1. 장비 성능 저하</span><i style="width:70px"></i><b>6건</b></div><div><span>2. 전원 불안정</span><i style="width:50px"></i><b>4건</b></div><div><span>3. 네트워크 지연</span><i style="width:35px"></i><b>3건</b></div></div><div class="cause-ranks"><b>유형별 현황</b><div><span>ATS 6건</span><i style="width:65px"></i><b>37%</b></div><div><span>Network 4건</span><i style="width:45px"></i><b>25%</b></div><div><span>설비 3건</span><i style="width:30px"></i><b>18%</b></div></div></div><div class="dash-mini-chart"><h4>반복 고장 상위 역사</h4><div class="cause-ranks"><div><span>TOP 1　계양</span><b></b><strong>5건</strong></div><div><span>TOP 2　김포공항</span><b></b><strong>3건</strong></div><div><span>TOP 3　인천공항T1</span><b></b><strong>2건</strong></div></div></div></div></section>`}
function modernDashboard(){return `<iframe id="plannerDashboardFrame" class="planner-dashboard-frame" src="${CONTEXT_PATH}/planner/dashboard-map/index.html" title="TNMS 통합 대시보드"></iframe>`}
function setDashboardSlide(index){
  const frame=document.getElementById('plannerDashboardFrame');
  if(frame)frame.src=CONTEXT_PATH+(index===0?'/planner/dashboard-map/index.html':'/planner/dashboard-system/index.html');
}

window.addEventListener('message',function(event){
  if(event.origin!==location.origin||!event.data||event.data.source!=='tnms-planner')return;
  if(event.data.type==='dashboard-slide')setDashboardSlide(Number(event.data.index)||0);
  if(event.data.type==='navigate'&&event.data.key)render(event.data.key);
});

const facilityStations=['전체','서울역','공덕','홍대입구','DMC','마곡나루','김포공항','계양','검암','청라','영종','운서'];
function facilityRoute(){return `<div class="card facility-route-card"><h3 class="facility-route-title">역사 현황</h3><div class="facility-route">${facilityStations.map((name,i)=>`<div class="station-node ${i===6?'selected bad':i===7?'warn':''}">${name}<i></i></div>`).join('')}</div><div class="facility-legend"><span>정상</span><span class="warn">주의</span><span class="bad">장애</span><span class="off">통신단절</span></div></div>`}
function facilityDetail(config){return `<div class="card facility-content"><div class="facility-detail"><div><div class="facility-sidebox"><h4>시스템 요약</h4><div class="facility-metric"><span>총 등록장비</span><b>${config.total}</b></div><div class="facility-metric"><span>정상 장비</span><b class="c-green">${config.normal}</b></div><div class="facility-metric"><span>주의 장비</span><b class="c-yellow">1대</b></div><div class="facility-metric"><span>장애 장비</span><b class="c-red">1대</b></div></div><div class="facility-sidebox"><h4>${config.core} 상태</h4>${[['CPU 사용률','18.2%'],['Memory 사용률','32.6%'],['Disk 사용률','28.4%'],['Network 사용률','21.7%']].map((x,i)=>`<div class="gauge-row"><label>${x[0]}</label><div class="progress"><i style="width:${18+i*7}%"></i></div><b>${x[1]}</b></div>`).join('')}</div><div class="facility-sidebox"><h4>이벤트 요약 <small>(24시간)</small></h4><div class="facility-metric"><span class="c-red">● 장애</span><b>1건</b></div><div class="facility-metric"><span class="c-yellow">● 주의</span><b>1건</b></div><div class="facility-metric"><span>● 정보</span><b>3건</b></div></div></div><div class="facility-topology"><h3>${config.name} 구성도</h3><div class="topology-core"><b>${config.core}</b><br><small>김포공항역 ${config.name}</small><div class="chip" style="margin-top:10px">정상</div></div><div class="topology-branches"><div class="topology-branch"><h4>${config.branch1}</h4><small>${config.branch1Desc}</small><div class="facility-status-pills"><span class="status-pill"><i></i>정상 ${Math.max(1,parseInt(config.total)-2)}</span><span class="status-pill warn"><i></i>주의 1</span><span class="status-pill bad"><i></i>장애 1</span></div><table><tr><th>장비명</th><th>위치</th><th>상태</th><th>내용</th></tr><tr><td>${config.branch1} #2</td><td>승강장 2번</td><td class="c-yellow">주의</td><td>응답 지연</td></tr><tr><td>${config.branch1} #5</td><td>승강장 5번</td><td class="c-red">장애</td><td>통신 장애</td></tr></table></div><div class="topology-branch"><h4>${config.branch2}</h4><small>${config.branch2Desc}</small><div class="facility-status-pills"><span class="status-pill"><i></i>정상 ${Math.max(1,parseInt(config.total)-1)}</span><span class="status-pill warn"><i></i>주의 0</span><span class="status-pill bad"><i></i>장애 0</span></div><div class="callout" style="margin-top:24px">주의·장애건의 추가 정보가 없습니다.</div></div></div></div></div></div>`}
function statusCell(status){const type=status==='장애'?'bad':status==='주의'?'warn':status==='통신단절'?'off':'';return chip(status,type)}
function facilityList(config){return `<div class="card facility-content"><div class="facility-content-head"><h3>${config.name} 장비 목록 <small>선택 0건</small></h3><div><input class="input wide" placeholder="장비명 / 장비 ID 검색"> <button class="btn primary">검색</button></div></div><b style="font-size:11px">총 40건</b><table><thead><tr><th style="width:42px">□</th><th style="width:48px">NO.</th>${config.headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${config.rows.map((row,i)=>`<tr><td>□</td><td>${i+1}</td>${row.map((value,index)=>`<td>${index===0?statusCell(value):value}</td>`).join('')}<td>${config.key==='scada'&&i===0?'<button class="btn sm" onclick="openFacilityFaultModal()">장애 상세</button>':'<button class="btn sm">수정</button>'}</td></tr>`).join('')}</tbody></table><div style="display:flex;align-items:center;margin-top:12px"><button class="btn primary">+ 추가</button><button class="btn danger" style="margin-left:8px">삭제</button><div style="margin-left:auto" class="pager"><div class="page">‹</div><div class="page on">1</div><div class="page">2</div><div class="page">3</div><div class="page">›</div></div></div></div>`}
function facilityScreen(config){const detailActive=config.defaultView!=='list';return modernLayout(config.key,`${facilityRoute()}<div class="card facility-selection"><h2>김포공항 · ${config.name}</h2><button class="alert-count">장애 1건</button><button class="alert-count warn">주의 1건</button><span class="spacer"></span></div><div class="card facility-tabs"><button class="facility-tab ${detailActive?'active':''}" data-facility-tab="detail" onclick="setFacilityTab('detail')">상세 현황</button><button class="facility-tab ${detailActive?'':'active'}" data-facility-tab="list" onclick="setFacilityTab('list')">장비목록</button></div><div id="facilityDetailPane" style="display:${detailActive?'block':'none'}">${facilityDetail(config)}</div><div id="facilityListPane" style="display:${detailActive?'none':'block'}">${facilityList(config)}</div>`)}
function setFacilityTab(view){document.getElementById('facilityDetailPane').style.display=view==='detail'?'block':'none';document.getElementById('facilityListPane').style.display=view==='list'?'block':'none';document.querySelectorAll('[data-facility-tab]').forEach(el=>el.classList.toggle('active',el.dataset.facilityTab===view))}
function rows(prefix,name,type){return Array.from({length:10},(_,i)=>[i===0?'장애':i===2||i===5?'주의':'정상',`${prefix}-${String(i+1).padStart(3,'0')}`,`${name} ${String(i+1).padStart(2,'0')}`,type,`192.168.10.${101+i}`,'김포공항',i===0?'수신지연':'18.2%',i===0?'수신지연':'32.6%',i===0?'수신지연':'10:3'+i+':11'])}
const transmissionConfig={key:'systems',name:'전송설비',total:'16대',normal:'14대',core:'NMS',branch1:'전송 스위치',branch1Desc:'역사 전송망 주요 스위치',branch2:'광전송 장치',branch2Desc:'광링크 및 통신상태',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('TX','전송장비','L3 스위치'),defaultView:'detail'};
const pidsRows=Array.from({length:10},(_,i)=>[i===0||i===6?'장애':i===2||i===5?'주의':'정상','위치 확인 필요',`승강장 표시장치 ${String(i+1).padStart(2,'0')}`,'-','-','DB 확인 필요','DB 확인 필요','DB 확인 필요','DB 확인 필요']);
const pidsConfig={key:'equipment',name:'행선안내설비',total:'16대',normal:'14대',core:'LSE',branch1:'승강장 표시장치',branch1Desc:'하부 연동 시스템: CCTV, 시계, 열차진출입정보',branch2:'대합실 표시장치',branch2Desc:'하부 연동 시스템 정보 미제공',headers:['상태','위치','장비명','IP','최근응답','CCTV','시계','화재경보기','열차진출입정보','관리'],rows:pidsRows,defaultView:'detail'};
const switchConfig={key:'switch',name:'전화교환설비',total:'24대',normal:'22대',core:'교환 서버',branch1:'교환기 주 장치',branch1Desc:'역사별 전화교환 제어',branch2:'교환기 SW',branch2Desc:'가입자 및 통화채널 상태',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('PBX','전화교환장비','교환기'),defaultView:'detail'};
const cctvRows=Array.from({length:10},(_,i)=>[i===0?'장애':i===5?'주의':'정상',`CCTV-PF-${String(i+1).padStart(2,'0')}`,`플랫폼 ${i+1}`,`192.168.10.${101+i}`,'XND-6020R',`00:09:18:51:${String(i).padStart(2,'0')}:A${i}`,i===0?'중단':'녹화 중',i===0?'장애':'정상',`2026-05-22 10:3${i}:11`]);
const cctvConfig={key:'cctv',name:'영상감시설비(CCTV)',total:'40대',normal:'38대',core:'NVR',branch1:'역사 CCTV',branch1Desc:'승강장·대합실 카메라',branch2:'녹화 서버',branch2Desc:'NVR 녹화 및 저장상태',headers:['상태','카메라명','위치','IP 주소','모델','MAC 주소','녹화','통신','마지막 확인','관리'],rows:cctvRows,defaultView:'list'};
const scadaConfig={key:'scada',name:'SCADA 출입보안설비',total:'40대',normal:'38대',core:'SCADA 제어기',branch1:'출입통제 컨트롤러',branch1Desc:'역사 보안구역 출입 제어',branch2:'출입문 단말',branch2Desc:'게이트·도어 상태 감시',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('SCADA','SCADA 장비','출입통제'),defaultView:'list'};
function openFacilityFaultModal(){showModal(`<div class="modal-head"><h2>장애 상세보기</h2><button class="modal-close" onclick="closeModal()">×</button></div><div class="card-title"><span><b class="c-red">● 컨트롤러 통신 장애</b>　${chip('장애 1건','bad')}</span></div><h3>기본 정보</h3><div class="form-grid"><div class="label">시스템</div><div class="field">SCADA 출입보안설비</div><div class="label">장비 ID</div><div class="field">SCADA-001</div><div class="label">역사</div><div class="field">김포공항역</div><div class="label">장비 IP</div><div class="field">192.168.10.101</div><div class="label">장애 발생 시간</div><div class="field">2026-05-22 10:28:11</div><div class="label">장애 등급</div><div class="field c-red">장애</div></div><h3 style="margin-top:20px">장애 상세 정보</h3><div class="form-grid"><div class="label">장애 발생 위치</div><div class="field">김포공항 제어실</div><div class="label">발생 여부</div><div class="field">발생</div><div class="label">장애 종류</div><div class="field">컨트롤러 통신 장애</div><div class="label">장애 설명</div><div class="field">EVENT 수신값 표시</div></div><h3 style="margin-top:20px">조치 이력</h3><table><tr><th>조치 시간</th><th>조치자</th><th>조치 내용</th><th>조치 결과</th></tr><tr><td colspan="4" class="empty-row">연동된 조치 이력이 없습니다.</td></tr></table><div class="modal-actions"><button class="btn" onclick="closeModal()">닫기</button><button class="btn primary" onclick="closeModal()">확인</button></div>`)}

sidebar=modernSidebar;
layout=modernLayout;
dashboard=modernDashboard;
systems=()=>facilityScreen(transmissionConfig);
equipment=()=>facilityScreen(pidsConfig);
switchScreen=()=>facilityScreen(switchConfig);
cctv=()=>facilityScreen(cctvConfig);
scada=()=>facilityScreen(scadaConfig);

function enhanceTables(scope=document){scope.querySelectorAll('table').forEach(table=>{const columns=table.querySelectorAll('tr:first-child > th').length;if(columns>=8)table.classList.add('table-wide-xl');else if(columns>=6)table.classList.add('table-wide');if(!table.parentElement.classList.contains('table-scroll')){const scroll=document.createElement('div');scroll.className='table-scroll';table.parentNode.insertBefore(scroll,table);scroll.appendChild(table)}})}
const pages={dashboard,route:routeScreen,systems,equipment,switch:switchScreen,cctv,video,scada,cycle,threshold,performance:performanceScreen,raw,faults,faultHistory,exceptions,faultTypes,reports,users:usersScreen,auth,applications,notify,settings,logs};
function render(key){
  if(!hasPermission(key,'listAuthrtYn'))key=hasPermission('dashboard','listAuthrtYn')?'dashboard':Object.keys(PERMISSIONS).find(k=>hasPermission(k,'listAuthrtYn'))||'dashboard';
  document.getElementById('root').innerHTML=(pages[key]||dashboard)();
  enhanceTables();
  document.querySelectorAll('.route').forEach(routeEl=>{
    if(routeEl.parentElement.classList.contains('route-scroll'))return;
    const scroll=document.createElement('div');
    scroll.className='route-scroll';
    routeEl.parentNode.insertBefore(scroll,routeEl);
    scroll.appendChild(routeEl);
  });
  document.querySelectorAll('.nav-item[data-key]').forEach(el=>{
    el.onclick=()=>{const next=el.dataset.key;if(!next)return;if(!hasPermission(next,'listAuthrtYn')){showToast('해당 화면에 대한 접근 권한이 없습니다.',true);return}history.replaceState(null,'',`?screen=${next}`);render(next)};
  });
  if(key==='users'){loadAuthOptions().then(loadUsers).catch(e=>showToast(e.message,true))}
  if(key==='auth')loadAuths();
}
async function bootstrapPermissions(shouldRender=true){
  try{const data=await api('/auth/myPermissions.ajax');CURRENT_USER=data.user||CURRENT_USER;PERMISSIONS=data.permissions||{};CSRF_TOKEN=data.csrfToken||CSRF_TOKEN;if(shouldRender)render(new URLSearchParams(location.search).get('screen')||'dashboard')}catch(e){showToast(e.message,true)}
}
bootstrapPermissions(true);
</script></body></html>
