/*
 * TNMS 설비관리 5개 화면 UI 확인용 최소 샘플 보강
 * - 기존 데이터는 삭제하지 않음
 * - 이미 동일 관리번호가 있으면 중복 생성하지 않음
 * - 행선안내 HSE Sub가 없을 때만 추가
 */

INSERT INTO eqpmnt_info
(EQPMNT_MNG_NO, EQPMNT_NM, EQPMNT_SE_CD, EQPMNT_CLSF_CD, LINK_SYS_CD, EMS_ID, STN_CD,
 INSTL_PLC_NM, EQPMNT_IP_ADDR, EQPMNT_MDL_NM, EQPMNT_EXPLN, PING_MNTR_YN, PING_CYCLE_SEC,
 USE_YN, REG_DT, RGTR_ID)
SELECT 'UIUX-SAMPLE-PIDS-HSE-02', '행선안내 HSE Sub', 'HSE', NULL, 'EMS_PIDS', 'HSE-SUB-01',
       COALESCE((SELECT STN_CD FROM eqpmnt_info WHERE LINK_SYS_CD='EMS_PIDS' AND UPPER(EQPMNT_SE_CD)='LSE' AND USE_YN='Y' ORDER BY EQPMNT_SN LIMIT 1),'AREX06'),
       '통신기계실', '192.168.10.135', 'PIDS-HSE', '설비관리 화면 HSE Main/Sub 구성 확인용', 'Y', 30,
       'Y', NOW(), 'SYSTEM'
WHERE NOT EXISTS (
    SELECT 1 FROM eqpmnt_info
     WHERE LINK_SYS_CD='EMS_PIDS' AND USE_YN='Y'
       AND (EQPMNT_MNG_NO='UIUX-SAMPLE-PIDS-HSE-02' OR UPPER(EQPMNT_NM) LIKE '%HSE%SUB%')
);

INSERT INTO eqpmnt_stts
(EQPMNT_SN, CNTN_YN, PING_RSPNS_MS, STTS_CD, STTS_EXPLN, LAST_RSPNS_DT, CLCT_DT)
SELECT E.EQPMNT_SN, 'Y', 11, 'NORMAL', '정상 수신', NOW(), NOW()
  FROM eqpmnt_info E
 WHERE E.EQPMNT_MNG_NO='UIUX-SAMPLE-PIDS-HSE-02'
ON DUPLICATE KEY UPDATE CNTN_YN='Y', PING_RSPNS_MS=11, STTS_CD='NORMAL', STTS_EXPLN='정상 수신', LAST_RSPNS_DT=NOW(), CLCT_DT=NOW();

/* 화면 확인: 각 연계 시스템 장비 수/상태 확인 */
SELECT LINK_SYS_CD, COUNT(*) TOTAL_NOCS
  FROM eqpmnt_info
 WHERE USE_YN='Y' AND LINK_SYS_CD IN ('EMS_TX','EMS_PIDS','SCADA_SEC','PBX','VMS')
 GROUP BY LINK_SYS_CD
 ORDER BY FIELD(LINK_SYS_CD,'EMS_TX','EMS_PIDS','SCADA_SEC','PBX','VMS');
