/* 역사 대표색 우선순위를 설정 화면에서 관리하기 위한 설정값을 추가합니다. */
USE `arex_tnms`;

INSERT INTO ui_stng_info
(UI_STNG_CD, UI_STNG_NM, UI_STNG_VL, UI_STNG_EXPLN, USE_YN, RGTR_ID)
VALUES
('STATION_STATUS_PRIORITY', '역사 대표색 우선순위',
 'CRITICAL,OFFLINE,CAUTION,UNKNOWN,NORMAL',
 '앞에 위치한 상태부터 역사 대표색으로 우선 적용', 'Y', 'SYSTEM')
ON DUPLICATE KEY UPDATE
 UI_STNG_NM = VALUES(UI_STNG_NM),
 UI_STNG_EXPLN = VALUES(UI_STNG_EXPLN),
 USE_YN = 'Y',
 MDFCN_DT = NOW(),
 MDFR_ID = 'SYSTEM';

/* 화면 상태코드는 정상/주의/장애/통신단절/미수집 5개로 단일화합니다. */
UPDATE ui_stng_info
   SET UI_STNG_VL = REPLACE(UI_STNG_VL, 'WARNING', 'CAUTION'), MDFCN_DT = NOW(), MDFR_ID = 'SYSTEM'
 WHERE UI_STNG_CD = 'STATION_STATUS_PRIORITY';

UPDATE ui_stng_info
   SET UI_STNG_VL = 'CAUTION', MDFCN_DT = NOW(), MDFR_ID = 'SYSTEM'
 WHERE UI_STNG_CD IN ('ALRM_POPUP_GRD', 'ALRM_SOUND_GRD') AND UI_STNG_VL = 'WARNING';

UPDATE eqpmnt_stts SET STTS_CD = 'CAUTION' WHERE STTS_CD = 'WARNING';

INSERT INTO com_cd_info
(COM_CD_GROUP_ID, COM_CD, COM_CD_NM, COM_CD_EXPLN, COM_CD_SEQ, COM_CD_USE_YN, EXT1_CN, EXT2_CN, RGTR_ID)
VALUES
('SYS_STTS', 'CAUTION', '주의', '주의 상태', 2, 'Y', '#FFCC66', NULL, 'SYSTEM')
ON DUPLICATE KEY UPDATE
 COM_CD_NM = VALUES(COM_CD_NM), COM_CD_USE_YN = 'Y',
 EXT1_CN = COALESCE(NULLIF(EXT1_CN, ''), VALUES(EXT1_CN)), MDFCN_DT = NOW(), MDFR_ID = 'SYSTEM';

DELETE FROM com_cd_info WHERE COM_CD_GROUP_ID = 'SYS_STTS' AND COM_CD = 'WARNING';

/* 통신단절도 이벤트 등급·컬러 관리 표에서 관리할 수 있도록 공통코드에 추가합니다. */
UPDATE com_cd_info
   SET COM_CD_SEQ = 6, MDFCN_DT = NOW(), MDFR_ID = 'SYSTEM'
 WHERE COM_CD_GROUP_ID = 'SYS_STTS' AND COM_CD = 'UNKNOWN' AND COM_CD_SEQ = 5;

INSERT INTO com_cd_info
(COM_CD_GROUP_ID, COM_CD, COM_CD_NM, COM_CD_EXPLN, COM_CD_SEQ, COM_CD_USE_YN, EXT1_CN, EXT2_CN, RGTR_ID)
VALUES
('SYS_STTS', 'OFFLINE', '통신단절', '수집주기 또는 연결상태 기준 통신단절', 5, 'Y', '#8290A6', NULL, 'SYSTEM')
ON DUPLICATE KEY UPDATE
 COM_CD_NM = VALUES(COM_CD_NM),
 COM_CD_EXPLN = VALUES(COM_CD_EXPLN),
 COM_CD_USE_YN = 'Y',
 EXT1_CN = COALESCE(NULLIF(EXT1_CN, ''), VALUES(EXT1_CN)),
 MDFCN_DT = NOW(),
 MDFR_ID = 'SYSTEM';
