-- TNMS UI/UX 화면의 기존 가데이터를 DB 조회 방식으로 전환하기 위한 초기 데이터
-- 적용 순서: arex_tnms 260914.sql 적용 후 본 파일 실행
-- 기존 운영 데이터는 삭제하지 않으며 UIUX-SAMPLE-* 관리번호/장애번호만 재실행 가능하게 갱신함

INSERT INTO stn_info
(STN_CD, STN_NM, RTE_NO, RTE_NM, STN_SEQ, MNLS_STN_YN, USE_YN, RGTR_ID)
VALUES
('MNLS01','기지SS','AREX','공항철도',101,'Y','Y','SYSTEM'),
('MNLS02','차량기지','AREX','공항철도',102,'Y','Y','SYSTEM'),
('MNLS03','운서SSP','AREX','공항철도',103,'Y','Y','SYSTEM'),
('MNLS04','SIG2','AREX','공항철도',104,'Y','Y','SYSTEM'),
('MNLS05','청라SSP','AREX','공항철도',105,'Y','Y','SYSTEM'),
('MNLS06','통신통제실','AREX','공항철도',106,'Y','Y','SYSTEM'),
('MNLS07','계양SS','AREX','공항철도',107,'Y','Y','SYSTEM')
ON DUPLICATE KEY UPDATE STN_NM=VALUES(STN_NM), MNLS_STN_YN='Y', USE_YN='Y', MDFCN_DT=NOW(), MDFR_ID='SYSTEM';

INSERT INTO eqpmnt_info
(EQPMNT_MNG_NO, EQPMNT_NM, EQPMNT_SE_CD, LINK_SYS_CD, STN_CD, INSTL_PLC_NM,
 EQPMNT_IP_ADDR, EQPMNT_MDL_NM, PING_MNTR_YN, PING_CYCLE_SEC, EQPMNT_EXPLN, USE_YN, RGTR_ID)
VALUES
('UIUX-SAMPLE-VMS-01','플랫폼 CCTV 01','CCTV','VMS','AREX06','승강장 1번','192.168.10.101','XND-6020R','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-VMS-02','플랫폼 CCTV 02','CCTV','VMS','AREX06','승강장 2번','192.168.10.102','XND-6020R','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-VMS-03','계양역 CCTV 01','CCTV','VMS','AREX07','승강장 1번','192.168.10.103','XND-6020R','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-PBX-01','전화교환 주 장치','PBX','PBX','AREX06','통신기계실','192.168.10.111','PBX-MAIN','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-PBX-02','전화교환 보조 장치','PBX','PBX','AREX06','통신기계실','192.168.10.112','PBX-SUB','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-SCADA-01','출입통제 컨트롤러 01','SCADA','SCADA_SEC','AREX06','역무실','192.168.10.121','SCADA-CTRL','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-SCADA-02','출입문 단말 01','SCADA','SCADA_SEC','AREX06','보안구역','192.168.10.122','SCADA-DOOR','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-SCADA-03','계양역 출입통제 컨트롤러','SCADA','SCADA_SEC','AREX07','역무실','192.168.10.123','SCADA-CTRL','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-PIDS-01','승강장 표시장치 01','PIDS','EMS_PIDS','AREX06','승강장 1번','192.168.10.131','PIDS-DISPLAY','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-PIDS-02','대합실 표시장치 01','PIDS','EMS_PIDS','AREX06','대합실','192.168.10.132','PIDS-DISPLAY','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-TX-01','전송 스위치 01','TRANSMISSION','EMS_TX','AREX06','통신기계실','192.168.10.141','L3-SWITCH','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM'),
('UIUX-SAMPLE-TX-02','광전송 장치 01','TRANSMISSION','EMS_TX','AREX06','통신기계실','192.168.10.142','OPTICAL-TX','Y',30,'UI/UX 초기 화면 데이터','Y','SYSTEM')
ON DUPLICATE KEY UPDATE EQPMNT_NM=VALUES(EQPMNT_NM), LINK_SYS_CD=VALUES(LINK_SYS_CD), STN_CD=VALUES(STN_CD), INSTL_PLC_NM=VALUES(INSTL_PLC_NM), EQPMNT_IP_ADDR=VALUES(EQPMNT_IP_ADDR), USE_YN='Y', MDFCN_DT=NOW(), MDFR_ID='SYSTEM';

INSERT INTO eqpmnt_stts (EQPMNT_SN, CNTN_YN, PING_RSPNS_MS, STTS_CD, STTS_EXPLN, LAST_RSPNS_DT, CLCT_DT)
SELECT EQPMNT_SN,
       CASE WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-PBX-01' THEN 'N' ELSE 'Y' END,
       CASE WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-PBX-01' THEN NULL ELSE 18 END,
       CASE
         WHEN EQPMNT_MNG_NO IN ('UIUX-SAMPLE-VMS-01','UIUX-SAMPLE-PBX-01','UIUX-SAMPLE-SCADA-01') THEN 'CRITICAL'
         WHEN EQPMNT_MNG_NO IN ('UIUX-SAMPLE-VMS-03','UIUX-SAMPLE-SCADA-03','UIUX-SAMPLE-TX-01') THEN 'CAUTION'
         ELSE 'NORMAL'
       END,
       CASE
         WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-VMS-01' THEN '영상 수신 중단'
         WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-PBX-01' THEN '통신 단절'
         WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-SCADA-01' THEN '응답 지연'
         WHEN EQPMNT_MNG_NO IN ('UIUX-SAMPLE-VMS-03','UIUX-SAMPLE-SCADA-03') THEN '주의 임계치 감지'
         WHEN EQPMNT_MNG_NO='UIUX-SAMPLE-TX-01' THEN '패킷 응답 지연'
         ELSE '정상 수신'
       END,
       NOW(), NOW()
  FROM eqpmnt_info WHERE EQPMNT_MNG_NO LIKE 'UIUX-SAMPLE-%'
ON DUPLICATE KEY UPDATE CNTN_YN=VALUES(CNTN_YN), PING_RSPNS_MS=VALUES(PING_RSPNS_MS), STTS_CD=VALUES(STTS_CD), STTS_EXPLN=VALUES(STTS_EXPLN), LAST_RSPNS_DT=VALUES(LAST_RSPNS_DT), CLCT_DT=VALUES(CLCT_DT);

-- 대시보드 상태 판정 기준
-- 1) CNTN_YN='N' 또는 최종 수집시각(CLCT_DT)이 현재보다 5분 이상 이전이면 통신단절
-- 2) 장애(CRITICAL) > 통신단절(OFFLINE) > 주의(CAUTION) > 미수집(UNKNOWN) > 정상(NORMAL) 순으로 역사 대표 상태 표시

INSERT INTO eqpmnt_perf_stts (EQPMNT_SN, PERF_IDCT_CD, MSRMT_VL, UNIT_NM, STTS_CD, CLCT_DT)
SELECT EQPMNT_SN, 'CPU_USGRT', 18.2, '%', 'NORMAL', NOW()
  FROM eqpmnt_info WHERE EQPMNT_MNG_NO LIKE 'UIUX-SAMPLE-%'
ON DUPLICATE KEY UPDATE MSRMT_VL=VALUES(MSRMT_VL), UNIT_NM=VALUES(UNIT_NM), STTS_CD=VALUES(STTS_CD), CLCT_DT=VALUES(CLCT_DT);

INSERT INTO eqpmnt_perf_stts (EQPMNT_SN, PERF_IDCT_CD, MSRMT_VL, UNIT_NM, STTS_CD, CLCT_DT)
SELECT EQPMNT_SN, 'MMRY_USGRT', 32.6, '%', 'NORMAL', NOW()
  FROM eqpmnt_info WHERE EQPMNT_MNG_NO LIKE 'UIUX-SAMPLE-%'
ON DUPLICATE KEY UPDATE MSRMT_VL=VALUES(MSRMT_VL), UNIT_NM=VALUES(UNIT_NM), STTS_CD=VALUES(STTS_CD), CLCT_DT=VALUES(CLCT_DT);

INSERT INTO dsblty_info
(DSBLTY_NO, EQPMNT_SN, DSBLTY_OCRN_PLC_NM, DSBLTY_GRD_CD, OCRN_RCVR_SE_CD,
 DSBLTY_OCRN_DT, DSBLTY_END_DT, DSBLTY_OCRN_CN, DSBLTY_RSN, DSBLTY_JGMT_CD,
 PRCS_STTS_CD, EXCP_APLY_YN, LAST_MDFCN_DT)
SELECT CONCAT('UIUX-', REPLACE(EQPMNT_MNG_NO,'UIUX-SAMPLE-','')),
       EQPMNT_SN, '김포공항역',
       CASE WHEN EQPMNT_MNG_NO LIKE '%VMS-01' OR EQPMNT_MNG_NO LIKE '%PBX-01' THEN 'CRITICAL' ELSE 'CAUTION' END,
       '1', TIMESTAMP('2026-09-14 10:28:11'),
       CASE WHEN EQPMNT_MNG_NO LIKE '%SCADA-01' THEN TIMESTAMP('2026-09-14 10:36:53') ELSE NULL END,
       STTS_EXPLN, STTS_EXPLN, 'SERVICE',
       CASE WHEN EQPMNT_MNG_NO LIKE '%SCADA-01' THEN 'COMPLETED' ELSE 'UNCONFIRMED' END,
       'N', NOW()
  FROM eqpmnt_info E JOIN eqpmnt_stts S USING(EQPMNT_SN)
 WHERE EQPMNT_MNG_NO IN ('UIUX-SAMPLE-VMS-01','UIUX-SAMPLE-PBX-01','UIUX-SAMPLE-SCADA-01','UIUX-SAMPLE-TX-01')
ON DUPLICATE KEY UPDATE DSBLTY_GRD_CD=VALUES(DSBLTY_GRD_CD), DSBLTY_END_DT=VALUES(DSBLTY_END_DT), DSBLTY_OCRN_CN=VALUES(DSBLTY_OCRN_CN), PRCS_STTS_CD=VALUES(PRCS_STTS_CD), LAST_MDFCN_DT=NOW();

INSERT INTO ui_stng_info
(UI_STNG_CD, UI_STNG_NM, UI_STNG_VL, UI_STNG_EXPLN, USE_YN, RGTR_ID)
VALUES
('ALRM_POPUP_GRD','장애 팝업 등급','CAUTION','해당 등급 이상 팝업','Y','SYSTEM'),
('ALRM_SOUND_GRD','장애 사운드 등급','CRITICAL','해당 등급 이상 사운드','Y','SYSTEM'),
('DASHBOARD_55IN_USE_YN','55인치 표준모드','Y','통합 대시보드 TV 표출 여부','Y','SYSTEM'),
('DASHBOARD_REFRESH_SEC','대시보드 갱신주기','10','대시보드 자동 갱신 초','Y','SYSTEM'),
('DASHBOARD_OFFLINE_MIN','통신단절 판정시간','5','최종 수집 후 통신단절로 판정할 경과시간(분)','Y','SYSTEM'),
('STATION_STATUS_PRIORITY','역사 대표색 우선순위','CRITICAL,OFFLINE,CAUTION,UNKNOWN,NORMAL','앞에 위치한 상태부터 역사 대표색으로 우선 적용','Y','SYSTEM'),
('LIST_ROW_CNT','페이지당 목록 수','20','목록 화면의 페이지당 기본 행 수','Y','SYSTEM'),
('PSWD_CHG_NOTICE_DAY','비밀번호 변경주기','6','비밀번호 변경 안내 주기(개월)','Y','SYSTEM'),
('PUSH_FAULT_YN','장애 알림','Y','장애 발생 푸시 알림 사용 여부','Y','SYSTEM'),
('PUSH_ACTION_YN','장애조치 알림','Y','장애 조치 푸시 알림 사용 여부','Y','SYSTEM')
ON DUPLICATE KEY UPDATE UI_STNG_NM=VALUES(UI_STNG_NM), UI_STNG_VL=VALUES(UI_STNG_VL),
 UI_STNG_EXPLN=VALUES(UI_STNG_EXPLN), USE_YN='Y', MDFCN_DT=NOW(), MDFR_ID='SYSTEM';

UPDATE com_cd_info
   SET COM_CD_SEQ = 6, MDFCN_DT = NOW(), MDFR_ID = 'SYSTEM'
 WHERE COM_CD_GROUP_ID = 'SYS_STTS' AND COM_CD = 'UNKNOWN' AND COM_CD_SEQ = 5;

INSERT INTO com_cd_info
(COM_CD_GROUP_ID, COM_CD, COM_CD_NM, COM_CD_EXPLN, COM_CD_SEQ, COM_CD_USE_YN, EXT1_CN, EXT2_CN, RGTR_ID)
VALUES
('SYS_STTS', 'OFFLINE', '통신단절', '수집주기 또는 연결상태 기준 통신단절', 5, 'Y', '#8290A6', NULL, 'SYSTEM')
ON DUPLICATE KEY UPDATE COM_CD_NM=VALUES(COM_CD_NM), COM_CD_EXPLN=VALUES(COM_CD_EXPLN),
 COM_CD_USE_YN='Y', EXT1_CN=COALESCE(NULLIF(EXT1_CN, ''), VALUES(EXT1_CN)), MDFCN_DT=NOW(), MDFR_ID='SYSTEM';

UPDATE eqpmnt_stts SET STTS_CD='CAUTION' WHERE STTS_CD='WARNING';
INSERT INTO com_cd_info
(COM_CD_GROUP_ID, COM_CD, COM_CD_NM, COM_CD_EXPLN, COM_CD_SEQ, COM_CD_USE_YN, EXT1_CN, EXT2_CN, RGTR_ID)
VALUES ('SYS_STTS','CAUTION','주의','주의 상태',2,'Y','#FFCC66',NULL,'SYSTEM')
ON DUPLICATE KEY UPDATE COM_CD_NM=VALUES(COM_CD_NM), COM_CD_USE_YN='Y',
 EXT1_CN=COALESCE(NULLIF(EXT1_CN,''),VALUES(EXT1_CN)), MDFCN_DT=NOW(), MDFR_ID='SYSTEM';
DELETE FROM com_cd_info WHERE COM_CD_GROUP_ID='SYS_STTS' AND COM_CD='WARNING';
