const REMOVED_MENU_NAMES = new Set(['역사·선로 현황','CCTV 영상관리','알림·SMS 설정']);
function auth(){
  const actions=permissionButton('auth','regAuthrtYn','권한 추가','primary','openAuthModal()');
  return layout('auth',`<div class="split"><div class="card"><div class="card-title">권한 목록</div><div class="tree" id="authRows"><div class="row">조회 중입니다.</div></div></div><div class="card" id="authDetail"><div class="empty-row">왼쪽에서 권한을 선택해 주세요.</div></div></div>`,actions)
};
let CURRENT_AUTH_SN=null;
let CURRENT_AUTH_DATA=null;
async function loadAuths(selected){
  try{const list=await api('/auth/list.ajax');const target=selected||CURRENT_AUTH_SN||(list[0]&&list[0].authrtSn);document.getElementById('authRows').innerHTML=list.length?list.map(a=>`<div class="row clickable ${String(a.authrtSn)===String(target)?'sel':''}" onclick="loadAuthDetail(${a.authrtSn})">${escapeHtml(a.authrtNm)} <span class="count">${a.userNocs||0}명</span></div>`).join(''):'<div class="row">등록된 권한이 없습니다.</div>';if(target)await loadAuthDetail(target,false)}catch(e){showToast(e.message,true)}
}
async function loadAuthDetail(authrtSn,reloadList=true){
  try{CURRENT_AUTH_SN=authrtSn;const a=await api('/auth/detail.ajax?authrtSn='+authrtSn);const visibleMenuAuth=(a.menuAuthList||[]).filter(m=>!REMOVED_MENU_NAMES.has(m.menuNm));CURRENT_AUTH_DATA={authrtSn:a.authrtSn,authrtNm:a.authrtNm,authrtExpln:a.authrtExpln||''};if(reloadList){document.querySelectorAll('#authRows .row').forEach(x=>x.classList.remove('sel'));const rows=[...document.querySelectorAll('#authRows .row')];const row=rows.find(x=>x.getAttribute('onclick')&&x.getAttribute('onclick').includes('('+authrtSn+')'));if(row)row.classList.add('sel')}
    document.getElementById('authDetail').innerHTML=`<div class="card-title">메뉴·기능 권한 <small>${escapeHtml(a.authrtNm)}</small></div><div style="display:flex;gap:8px;margin-bottom:12px">${hasPermission('auth','mdfcnAuthrtYn')?`<button class="btn" onclick="openAuthModal(CURRENT_AUTH_DATA)">권한명 수정</button>`:''}${hasPermission('auth','delAuthrtYn')&&a.authrtSn!==1?`<button class="btn danger" onclick="deleteAuth(${a.authrtSn})">권한 삭제</button>`:''}</div><table class="matrix table-wide-xl"><thead><tr><th>메뉴</th><th>목록</th><th>상세</th><th>등록</th><th>수정</th><th>삭제</th><th>제어</th></tr></thead><tbody>${visibleMenuAuth.map(m=>`<tr data-menu-sn="${m.menuSn}"><td>${escapeHtml(m.menuNm)}</td>${['listAuthrtYn','dtlAuthrtYn','regAuthrtYn','mdfcnAuthrtYn','delAuthrtYn','ctrlAuthrtYn'].map(k=>`<td><input class="perm-check" type="checkbox" data-key="${k}" ${m[k]==='Y'?'checked':''} ${!hasPermission('auth','mdfcnAuthrtYn')||a.authrtSn===1?'disabled':''}></td>`).join('')}</tr>`).join('')}</tbody></table><div class="callout" style="margin-top:14px">상세·등록·수정·삭제·제어 권한을 선택하면 목록 권한이 자동으로 포함됩니다. 시스템 관리자 권한은 보호됩니다.</div>${hasPermission('auth','mdfcnAuthrtYn')&&a.authrtSn!==1?'<div class="modal-actions"><button class="btn primary" onclick="savePermissions()">권한 저장</button></div>':''}`;enhanceTables(document.getElementById('authDetail'));
  }catch(e){showToast(e.message,true)}
}
function openAuthModal(authData){const a=authData||{};showModal(`<div class="modal-head"><h2>${a.authrtSn?'권한 수정':'권한 등록'}</h2><button class="modal-close" onclick="closeModal()">×</button></div><form id="authForm"><input type="hidden" name="authrtSn" value="${a.authrtSn||''}"><div class="edit-form"><label>권한명 *</label><div class="full"><input class="form-control" name="authrtNm" value="${escapeHtml(a.authrtNm||'')}" maxlength="100" required></div><label>권한 설명</label><div class="full"><input class="form-control" name="authrtExpln" value="${escapeHtml(a.authrtExpln||'')}" maxlength="4000"></div></div><input type="hidden" name="useYn" value="Y"><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">취소</button><button class="btn primary" type="submit">저장</button></div></form>`);document.getElementById('authForm').addEventListener('submit',saveAuth)}
async function saveAuth(e){e.preventDefault();const authrtSn=e.target.querySelector('[name=authrtSn]').value,edit=!!authrtSn;try{const data=await api(edit?'/auth/update.ajax':'/auth/insert.ajax',{method:'POST',body:new URLSearchParams(new FormData(e.target))});closeModal();showToast(edit?'권한을 수정했습니다.':'권한을 등록했습니다.');await loadAuths(edit?authrtSn:data.authrtSn)}catch(error){showToast(error.message,true)}}
async function deleteAuth(authrtSn){if(!confirm('선택한 권한을 삭제하시겠습니까?'))return;try{await api('/auth/delete.ajax',{method:'POST',body:new URLSearchParams({authrtSn})});CURRENT_AUTH_SN=null;showToast('권한을 삭제했습니다.');await loadAuths()}catch(e){showToast(e.message,true)}}
async function savePermissions(){const rows=[...document.querySelectorAll('#authDetail tbody tr')];const menuAuthList=rows.map(row=>{const item={menuSn:Number(row.dataset.menuSn)};row.querySelectorAll('input[data-key]').forEach(input=>item[input.dataset.key]=input.checked?'Y':'N');return item});try{await api('/auth/savePermissions.ajax',{method:'POST',headers:{'Content-Type':'application/json;charset=UTF-8'},body:JSON.stringify({authrtSn:CURRENT_AUTH_SN,menuAuthList})});showToast('메뉴·기능 권한을 저장했습니다.');await bootstrapPermissions(false);await loadAuthDetail(CURRENT_AUTH_SN)}catch(e){showToast(e.message,true)}}

window.TNMS_PAGE_INIT = async function () {
  renderPage('auth', auth());
  await loadAuths();
};
