const USER_STATUS_LABELS={NORMAL:'정상',LOCKED:'잠금',SUSPENDED:'중지',DELETED:'삭제'};
const USER_TYPE_LABELS={INTERNAL:'내부',EXTERNAL:'외부'};
let USER_ID_CHECKED=false;
let USER_DATA=[];
let USER_PAGE=1;
let USER_PAGE_SIZE=20;

function usersScreen(){
  return layout('users',`<div class="account-planner-page">${typeof applicationsScreen==='function'?applicationsScreen():''}<section class="planner-card account-section user-section"><div class="planner-card-head"><div><h3>사용자 목록</h3><p>승인된 TNMS 사용자 계정과 권한·상태를 관리합니다.</p></div><small id="userCount">조회 중</small></div><div class="planner-filter-row account-filter"><select id="userAuthFilter" class="input"><option value="">전체 권한</option></select><select id="userStatusFilter" class="input"><option value="">전체 상태</option><option value="NORMAL">정상</option><option value="LOCKED">잠금</option><option value="SUSPENDED">중지</option></select><input id="userKeyword" class="input wide" placeholder="사용자 아이디 / 사용자명 / 소속"><button class="btn primary" type="button" onclick="loadUsers()">검색</button></div><div class="table-scroll"><table class="planner-table account-table"><thead><tr><th class="center"><input type="checkbox" onchange="toggleUserChecks(this.checked)"></th><th>No.</th><th>사용자 아이디</th><th>사용자명</th><th>소속</th><th>부서</th><th>전화번호</th><th>이메일</th><th>권한</th><th>상태</th><th>수정</th></tr></thead><tbody id="userRows"><tr><td class="empty-row" colspan="11">조회 중입니다.</td></tr></tbody></table></div><div id="userPager" class="planner-pager account-pager"></div><div class="account-bottom-actions">${hasPermission('users','delAuthrtYn')?'<button class="btn danger-outline" onclick="deleteSelectedUsers()">선택 삭제</button>':''}<span></span>${hasPermission('users','regAuthrtYn')?'<button class="btn primary" onclick="openUserModal()">+ 사용자 등록</button>':''}</div></section></div>`);
}
async function loadAuthOptions(){
  const list=await api('/auth/options.ajax');window.APPLICATION_AUTH_LIST=list||[];
  const select=document.getElementById('userAuthFilter');
  if(select){const current=select.value;select.innerHTML='<option value="">전체 권한</option>'+list.map(a=>`<option value="${escapeHtml(a.authrtCd)}">${escapeHtml(a.authrtNm)}</option>`).join('');select.value=current;}
  return list;
}
function userActionId(userId){return JSON.stringify(String(userId||''));}
function statusLabel(code){return USER_STATUS_LABELS[code]||code||'-';}
function userStateChip(code){const cls=code==='NORMAL'?'approved':code==='LOCKED'?'rejected':'waiting';return `<span class="planner-state ${cls}">${escapeHtml(statusLabel(code))}</span>`;}
function renderUserPager(){
  const pager=document.getElementById('userPager');if(!pager)return;const pages=Math.max(1,Math.ceil(USER_DATA.length/USER_PAGE_SIZE));USER_PAGE=Math.min(USER_PAGE,pages);if(pages<=1){pager.innerHTML='';return;}let html=`<button ${USER_PAGE===1?'disabled':''} onclick="changeUserPage(${USER_PAGE-1})">‹</button>`;const start=Math.max(1,USER_PAGE-2),end=Math.min(pages,start+4);for(let i=start;i<=end;i++)html+=`<button class="${i===USER_PAGE?'on':''}" onclick="changeUserPage(${i})">${i}</button>`;html+=`<button ${USER_PAGE===pages?'disabled':''} onclick="changeUserPage(${USER_PAGE+1})">›</button>`;pager.innerHTML=html;
}
function renderUsers(){
  const rows=document.getElementById('userRows');if(!rows)return;const start=(USER_PAGE-1)*USER_PAGE_SIZE,list=USER_DATA.slice(start,start+USER_PAGE_SIZE);rows.innerHTML=list.length?list.map((u,index)=>{const id=userActionId(u.userId);return `<tr><td class="center"><input type="checkbox" class="user-row-check" value="${escapeHtml(u.userId)}"></td><td>${start+index+1}</td><td><b>${escapeHtml(u.userId)}</b></td><td>${escapeHtml(u.userNm)}</td><td>${escapeHtml(u.ogdpBzentyNm||'-')}</td><td>${escapeHtml(u.deptNm||'-')}</td><td>${escapeHtml(u.mobileNo||u.telno||'-')}</td><td>${escapeHtml(u.emlAddr||'-')}</td><td>${escapeHtml(u.authrtNm||'-')}</td><td>${userStateChip(u.userSttsCd)}</td><td>${hasPermission('users','mdfcnAuthrtYn')?`<button class="btn sm" onclick='openUserModal(${id})'>수정</button>${u.userSttsCd==='LOCKED'?` <button class="btn sm" onclick='unlockUser(${id})'>잠금해제</button>`:''}`:'-'}</td></tr>`;}).join(''):'<tr><td class="empty-row" colspan="11">조회 결과가 없습니다.</td></tr>';renderUserPager();
}
window.changeUserPage=function(page){USER_PAGE=Math.max(1,page);renderUsers();};
async function loadUsers(){
  try{const params=new URLSearchParams(),auth=document.getElementById('userAuthFilter'),status=document.getElementById('userStatusFilter'),keyword=document.getElementById('userKeyword');if(auth&&auth.value)params.set('authrtCd',auth.value);if(status&&status.value)params.set('userSttsCd',status.value);if(keyword&&keyword.value.trim())params.set('searchKeyword',keyword.value.trim());USER_DATA=await api('/user/list.ajax?'+params.toString())||[];USER_PAGE=1;const count=document.getElementById('userCount');if(count)count.textContent=`총 ${USER_DATA.length}건`;renderUsers();}catch(e){showToast(e.message,true);}
}
function toggleUserChecks(checked){document.querySelectorAll('.user-row-check').forEach(x=>x.checked=checked);}
async function deleteSelectedUsers(){const ids=[...document.querySelectorAll('.user-row-check:checked')].map(x=>x.value);if(!ids.length){showToast('삭제할 사용자를 선택해 주세요.',true);return;}if(!confirm(`선택한 ${ids.length}개 사용자 계정을 삭제하시겠습니까?`))return;try{for(const userId of ids)await api('/user/delete.ajax',{method:'POST',body:new URLSearchParams({userId})});showToast(`${ids.length}개 사용자 계정을 삭제했습니다.`);await loadUsers();}catch(e){showToast(e.message,true);}}
async function openUserModal(userId){
  try{
    USER_ID_CHECKED=false;const edit=!!userId;const [authList,user]=await Promise.all([loadAuthOptions(),edit?api('/user/detail.ajax?userId='+encodeURIComponent(userId)):Promise.resolve({useYn:'Y',userSttsCd:'NORMAL',userSeCd:'INTERNAL'})]);const actionId=userActionId(user.userId||userId);
    showModal(`<div class="modal-head"><div><h2>${edit?'사용자 수정':'사용자 등록'}</h2><p>${edit?'계정 정보와 권한을 수정합니다.':'TNMS 사용자를 신규 등록합니다.'}</p></div><button class="modal-close" onclick="closeModal()">×</button></div><form id="userForm"><div class="edit-form planner-edit-form"><label>사용자 아이디 *</label><div><input class="form-control" name="userId" id="modalUserId" value="${escapeHtml(user.userId||'')}" ${edit?'readonly':''} required>${edit?'':'<div class="inline-field-action"><button type="button" class="btn sm" onclick="checkUserId()">중복 확인</button><span id="idCheckResult" class="form-help"></span></div>'}</div><label>사용자명 *</label><div><input class="form-control" name="userNm" value="${escapeHtml(user.userNm||'')}" required></div><label>사용자 구분 *</label><div><select class="form-control" name="userSeCd" required>${['INTERNAL','EXTERNAL'].map(c=>`<option value="${c}" ${c===(user.userSeCd||'INTERNAL')?'selected':''}>${USER_TYPE_LABELS[c]}</option>`).join('')}</select></div><label>소속업체</label><div><input class="form-control" name="ogdpBzentyNm" value="${escapeHtml(user.ogdpBzentyNm||'')}"></div><label>부서</label><div><input class="form-control" name="deptNm" value="${escapeHtml(user.deptNm||'')}"></div><label>휴대전화</label><div><input class="form-control" name="mobileNo" value="${escapeHtml(user.mobileNo||'')}" placeholder="하이픈 없이 숫자만"></div><label>전화번호</label><div><input class="form-control" name="telno" value="${escapeHtml(user.telno||'')}" placeholder="하이픈 없이 숫자만"></div><label>이메일</label><div><input class="form-control" name="emlAddr" type="email" value="${escapeHtml(user.emlAddr||'')}"></div><label>권한 *</label><div><select class="form-control" name="authrtCd" required>${authList.map(a=>`<option value="${escapeHtml(a.authrtCd)}" ${String(a.authrtCd)===String(user.authrtCd)?'selected':''}>${escapeHtml(a.authrtNm)}</option>`).join('')}</select></div><label>계정 상태</label><div><select class="form-control" name="userSttsCd">${['NORMAL','LOCKED','SUSPENDED'].map(c=>`<option value="${c}" ${c===(user.userSttsCd||'NORMAL')?'selected':''}>${USER_STATUS_LABELS[c]}</option>`).join('')}</select><input type="hidden" name="useYn" value="${user.useYn||'Y'}"></div><label>${edit?'새 비밀번호':'초기 비밀번호 *'}</label><div><input class="form-control" name="password" type="password" ${edit?'':'required'}><span class="form-help">영문·숫자·특수문자 포함 8~20자</span></div><label>비밀번호 확인</label><div><input class="form-control" name="passwordConfirm" type="password" ${edit?'':'required'}></div></div><div class="modal-actions">${edit&&hasPermission('users','delAuthrtYn')?`<button type="button" class="btn danger" onclick='deleteUser(${actionId})'>삭제</button>`:''}<button type="button" class="btn" onclick="closeModal()">취소</button><button type="submit" class="btn primary">저장</button></div></form>`);
    const form=document.getElementById('userForm');form.dataset.edit=edit?'Y':'N';form.addEventListener('submit',saveUser);if(!edit)document.getElementById('modalUserId').addEventListener('input',()=>{USER_ID_CHECKED=false;const result=document.getElementById('idCheckResult');if(result)result.textContent='';});
  }catch(e){showToast(e.message,true);}
}
async function checkUserId(){try{const id=document.getElementById('modalUserId').value.trim();const data=await api('/user/idCheck.ajax?userId='+encodeURIComponent(id));USER_ID_CHECKED=data.available;document.getElementById('idCheckResult').textContent=data.available?'사용 가능한 아이디입니다.':'이미 사용 중인 아이디입니다.';}catch(e){showToast(e.message,true);}}
async function saveUser(e){e.preventDefault();const form=e.target,edit=form.dataset.edit==='Y';if(!edit&&!USER_ID_CHECKED){showToast('아이디 중복 확인을 해주세요.',true);return;}try{await api(edit?'/user/update.ajax':'/user/insert.ajax',{method:'POST',body:new URLSearchParams(new FormData(form))});closeModal();showToast(edit?'사용자 정보를 수정했습니다.':'사용자를 등록했습니다.');await loadUsers();}catch(error){showToast(error.message,true);}}
async function deleteUser(userId){if(!confirm('선택한 사용자를 삭제하시겠습니까?'))return;try{await api('/user/delete.ajax',{method:'POST',body:new URLSearchParams({userId})});closeModal();showToast('사용자를 삭제했습니다.');await loadUsers();}catch(e){showToast(e.message,true);}}
async function unlockUser(userId){if(!confirm('계정 잠금을 해제하시겠습니까?'))return;try{await api('/user/unlock.ajax',{method:'POST',body:new URLSearchParams({userId})});showToast('계정 잠금을 해제했습니다.');await loadUsers();}catch(e){showToast(e.message,true);}}
window.TNMS_PAGE_INIT=async function(){USER_PAGE_SIZE=getListPageSize();renderPage('users',usersScreen());const appKeyword=document.getElementById('applicationKeyword'),userKeyword=document.getElementById('userKeyword');if(appKeyword)appKeyword.addEventListener('keydown',e=>{if(e.key==='Enter')loadApplications();});if(userKeyword)userKeyword.addEventListener('keydown',e=>{if(e.key==='Enter')loadUsers();});await loadAuthOptions();await Promise.all([loadUsers(),loadApplications()]);};
