const facilityStations=['전체','서울역','공덕','홍대입구','DMC','마곡나루','김포공항','계양','검암','청라','영종','운서'];
function facilityRoute(){return `<div class="card facility-route-card"><h3 class="facility-route-title">역사 현황</h3><div class="facility-route">${facilityStations.map((name,i)=>`<div class="station-node ${i===6?'selected bad':i===7?'warn':''}">${name}<i></i></div>`).join('')}</div><div class="facility-legend"><span>정상</span><span class="warn">주의</span><span class="bad">장애</span><span class="off">통신단절</span></div></div>`}
function facilityDetail(config){return `<div class="card facility-content"><div class="facility-detail"><div><div class="facility-sidebox"><h4>시스템 요약</h4><div class="facility-metric"><span>총 등록장비</span><b>${config.total}</b></div><div class="facility-metric"><span>정상 장비</span><b class="c-green">${config.normal}</b></div><div class="facility-metric"><span>주의 장비</span><b class="c-yellow">1대</b></div><div class="facility-metric"><span>장애 장비</span><b class="c-red">1대</b></div></div><div class="facility-sidebox"><h4>${config.core} 상태</h4>${[['CPU 사용률','18.2%'],['Memory 사용률','32.6%'],['Disk 사용률','28.4%'],['Network 사용률','21.7%']].map((x,i)=>`<div class="gauge-row"><label>${x[0]}</label><div class="progress"><i style="width:${18+i*7}%"></i></div><b>${x[1]}</b></div>`).join('')}</div><div class="facility-sidebox"><h4>이벤트 요약 <small>(24시간)</small></h4><div class="facility-metric"><span class="c-red">● 장애</span><b>1건</b></div><div class="facility-metric"><span class="c-yellow">● 주의</span><b>1건</b></div><div class="facility-metric"><span>● 정보</span><b>3건</b></div></div></div><div class="facility-topology"><h3>${config.name} 구성도</h3><div class="topology-core"><b>${config.core}</b><br><small>김포공항역 ${config.name}</small><div class="chip" style="margin-top:10px">정상</div></div><div class="topology-branches"><div class="topology-branch"><h4>${config.branch1}</h4><small>${config.branch1Desc}</small><div class="facility-status-pills"><span class="status-pill"><i></i>정상 ${Math.max(1,parseInt(config.total)-2)}</span><span class="status-pill warn"><i></i>주의 1</span><span class="status-pill bad"><i></i>장애 1</span></div><table><tr><th>장비명</th><th>위치</th><th>상태</th><th>내용</th></tr><tr><td>${config.branch1} #2</td><td>승강장 2번</td><td class="c-yellow">주의</td><td>응답 지연</td></tr><tr><td>${config.branch1} #5</td><td>승강장 5번</td><td class="c-red">장애</td><td>통신 장애</td></tr></table></div><div class="topology-branch"><h4>${config.branch2}</h4><small>${config.branch2Desc}</small><div class="facility-status-pills"><span class="status-pill"><i></i>정상 ${Math.max(1,parseInt(config.total)-1)}</span><span class="status-pill warn"><i></i>주의 0</span><span class="status-pill bad"><i></i>장애 0</span></div><div class="callout" style="margin-top:24px">주의·장애건의 추가 정보가 없습니다.</div></div></div></div></div></div>`}
function statusCell(status){const type=status==='장애'?'bad':status==='주의'?'warn':status==='통신단절'?'off':'';return chip(status,type)}
function facilityList(config){return `<div class="card facility-content"><div class="facility-content-head"><h3>${config.name} 장비 목록 <small>선택 0건</small></h3><div><input class="input wide" placeholder="장비명 / 장비 ID 검색"> <button class="btn primary">검색</button></div></div><b style="font-size:11px">총 40건</b><table><thead><tr><th style="width:42px">□</th><th style="width:48px">NO.</th>${config.headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${config.rows.map((row,i)=>`<tr><td>□</td><td>${i+1}</td>${row.map((value,index)=>`<td>${index===0?statusCell(value):value}</td>`).join('')}<td>${config.key==='scada'&&i===0?'<button class="btn sm" onclick="openFacilityFaultModal()">장애 상세</button>':'<button class="btn sm">수정</button>'}</td></tr>`).join('')}</tbody></table><div style="display:flex;align-items:center;margin-top:12px"><button class="btn primary">+ 추가</button><button class="btn danger" style="margin-left:8px">삭제</button><div style="margin-left:auto" class="pager"><div class="page">‹</div><div class="page on">1</div><div class="page">2</div><div class="page">3</div><div class="page">›</div></div></div></div>`}
function facilityScreen(config){const detailActive=config.defaultView!=='list';return layout(config.key,`${facilityRoute()}<div class="card facility-selection"><h2>김포공항 · ${config.name}</h2><button class="alert-count">장애 1건</button><button class="alert-count warn">주의 1건</button><span class="spacer"></span></div><div class="card facility-tabs"><button class="facility-tab ${detailActive?'active':''}" data-facility-tab="detail" onclick="setFacilityTab('detail')">상세 현황</button><button class="facility-tab ${detailActive?'':'active'}" data-facility-tab="list" onclick="setFacilityTab('list')">장비목록</button></div><div id="facilityDetailPane" style="display:${detailActive?'block':'none'}">${facilityDetail(config)}</div><div id="facilityListPane" style="display:${detailActive?'none':'block'}">${facilityList(config)}</div>`)}
function setFacilityTab(view){document.getElementById('facilityDetailPane').style.display=view==='detail'?'block':'none';document.getElementById('facilityListPane').style.display=view==='list'?'block':'none';document.querySelectorAll('[data-facility-tab]').forEach(el=>el.classList.toggle('active',el.dataset.facilityTab===view))}
function rows(prefix,name,type){return Array.from({length:10},(_,i)=>[i===0?'장애':i===2||i===5?'주의':'정상',`${prefix}-${String(i+1).padStart(3,'0')}`,`${name} ${String(i+1).padStart(2,'0')}`,type,`192.168.10.${101+i}`,'김포공항',i===0?'수신지연':'18.2%',i===0?'수신지연':'32.6%',i===0?'수신지연':'10:3'+i+':11'])}
const transmissionConfig={key:'systems',name:'전송설비',total:'16대',normal:'14대',core:'NMS',branch1:'전송 스위치',branch1Desc:'역사 전송망 주요 스위치',branch2:'광전송 장치',branch2Desc:'광링크 및 통신상태',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('TX','전송장비','L3 스위치'),defaultView:'detail'};
const pidsRows=Array.from({length:10},(_,i)=>[i===0||i===6?'장애':i===2||i===5?'주의':'정상','위치 확인 필요',`승강장 표시장치 ${String(i+1).padStart(2,'0')}`,'-','-','DB 확인 필요','DB 확인 필요','DB 확인 필요','DB 확인 필요']);
const pidsConfig={key:'equipment',name:'행선안내설비',total:'16대',normal:'14대',core:'LSE',branch1:'승강장 표시장치',branch1Desc:'하부 연동 시스템: CCTV, 시계, 열차진출입정보',branch2:'대합실 표시장치',branch2Desc:'하부 연동 시스템 정보 미제공',headers:['상태','위치','장비명','IP','최근응답','CCTV','시계','화재경보기','열차진출입정보','관리'],rows:pidsRows,defaultView:'detail'};
const switchConfig={key:'switch',name:'전화교환설비',total:'24대',normal:'22대',core:'교환 서버',branch1:'교환기 주 장치',branch1Desc:'역사별 전화교환 제어',branch2:'교환기 SW',branch2Desc:'가입자 및 통화채널 상태',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('PBX','전화교환장비','교환기'),defaultView:'detail'};
const cctvRows=Array.from({length:10},(_,i)=>[i===0?'장애':i===5?'주의':'정상',`CCTV-PF-${String(i+1).padStart(2,'0')}`,`플랫폼 ${i+1}`,`192.168.10.${101+i}`,'XND-6020R',`00:09:18:51:${String(i).padStart(2,'0')}:A${i}`,i===0?'중단':'녹화 중',i===0?'장애':'정상',`2026-05-22 10:3${i}:11`]);
const cctvConfig={key:'cctv',name:'영상감시설비(CCTV)',total:'40대',normal:'38대',core:'NVR',branch1:'역사 CCTV',branch1Desc:'승강장·대합실 카메라',branch2:'녹화 서버',branch2Desc:'NVR 녹화 및 저장상태',headers:['상태','카메라명','위치','IP 주소','모델','MAC 주소','녹화','통신','마지막 확인','관리'],rows:cctvRows,defaultView:'list'};
const scadaConfig={key:'scada',name:'SCADA 출입보안설비',total:'40대',normal:'38대',core:'SCADA 제어기',branch1:'출입통제 컨트롤러',branch1Desc:'역사 보안구역 출입 제어',branch2:'출입문 단말',branch2Desc:'게이트·도어 상태 감시',headers:['상태','장비 ID','장비 이름','장비 종류','장비 IP','역사','CPU','MEMORY','최근 수신','관리'],rows:rows('SCADA','SCADA 장비','출입통제'),defaultView:'list'};
function openFacilityFaultModal(){showModal(`<div class="modal-head"><h2>장애 상세보기</h2><button class="modal-close" onclick="closeModal()">×</button></div><div class="card-title"><span><b class="c-red">● 컨트롤러 통신 장애</b>　${chip('장애 1건','bad')}</span></div><h3>기본 정보</h3><div class="form-grid"><div class="label">시스템</div><div class="field">SCADA 출입보안설비</div><div class="label">장비 ID</div><div class="field">SCADA-001</div><div class="label">역사</div><div class="field">김포공항역</div><div class="label">장비 IP</div><div class="field">192.168.10.101</div><div class="label">장애 발생 시간</div><div class="field">2026-05-22 10:28:11</div><div class="label">장애 등급</div><div class="field c-red">장애</div></div><h3 style="margin-top:20px">장애 상세 정보</h3><div class="form-grid"><div class="label">장애 발생 위치</div><div class="field">김포공항 제어실</div><div class="label">발생 여부</div><div class="field">발생</div><div class="label">장애 종류</div><div class="field">컨트롤러 통신 장애</div><div class="label">장애 설명</div><div class="field">EVENT 수신값 표시</div></div><h3 style="margin-top:20px">조치 이력</h3><table><tr><th>조치 시간</th><th>조치자</th><th>조치 내용</th><th>조치 결과</th></tr><tr><td colspan="4" class="empty-row">연동된 조치 이력이 없습니다.</td></tr></table><div class="modal-actions"><button class="btn" onclick="closeModal()">닫기</button><button class="btn primary" onclick="closeModal()">확인</button></div>`)}

window.TNMS_PAGE_INIT = function () {
  const configs = {
    systems: transmissionConfig,
    equipment: pidsConfig,
    switch: switchConfig,
    cctv: cctvConfig,
    scada: scadaConfig
  };
  const pageKey = (window.TNMS_CONFIG || {}).pageKey;
  const pageConfig = configs[pageKey];
  if (!pageConfig) throw new Error('설비 화면 설정을 찾을 수 없습니다.');
  renderPage(pageKey, facilityScreen(pageConfig));
};
